# generated by datamodel-codegen:
#   filename:  api.json

from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import BaseModel, Field, RootModel


class AcceptOrgInviteRequestContent(BaseModel):
    orgId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    inviteId: str = Field(..., pattern='^[A-Za-z0-9-]+$')


class AuditOperation(StrEnum):
    """
    Database operations for audit tracking
    """

    insert = 'insert'
    update = 'update'
    delete = 'delete'
    access = 'access'
    export = 'export'
    share = 'share'


class AuditStatistics(BaseModel):
    """
    Audit statistics
    """

    totalEvents: float
    byTable: Any | None = Field(None, description='Breakdown by table name')
    byOperation: Any | None = Field(None, description='Breakdown by operation')
    topUsers: Any | None = Field(None, description='Most active users')


class AuthenticationErrorResponseContent(BaseModel):
    """
    Common error structures used across all operations
    """

    message: str


class CancelMeetingBotRequestContent(BaseModel):
    botId: str = Field(
        ...,
        description='Recall.ai bot identifier. Externally assigned by Recall; we treat it as an\nopaque UUID-shaped string.',
        pattern='^[A-Za-z0-9-]+$',
    )


class CancelMeetingBotResponseContent(BaseModel):
    success: bool


class CancelOrgInviteRequestContent(BaseModel):
    orgId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    inviteId: str = Field(..., pattern='^[A-Za-z0-9-]+$')


class ContentDisposition(StrEnum):
    """
    Content disposition for file downloads
    """

    inline = 'inline'
    attachment = 'attachment'


class Tag(RootModel[str]):
    root: str = Field(..., max_length=64, pattern='^[a-z0-9]+(-[a-z0-9]+)*$')


class DealId(RootModel[str]):
    root: str = Field(..., pattern='^[A-Za-z0-9-]+$')


class DealVersionId(RootModel[str]):
    root: str = Field(..., pattern='^[A-Za-z0-9-]+$')


class CreateFileRequestContent(BaseModel):
    orgId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    fileName: str
    sizeBytes: float
    fileType: str | None = Field(None, description='MIME type')
    folderPath: str | None = Field(None, description='Virtual folder path')
    tags: list[Tag] | None = Field(None, description='User-defined tags')
    dealIds: list[DealId] | None = Field(None, description='Associated deal IDs')
    dealVersionIds: list[DealVersionId] | None = Field(
        None, description='Associated deal version IDs'
    )
    requestUploadUrl: bool | None = Field(
        None, description='Request upload URL in response'
    )


class CreateMeetingBotRequestContent(BaseModel):
    meetingUrl: str = Field(
        ...,
        description='Video meeting URL the bot should join (Zoom / Meet / Teams).',
        pattern='^(https?:\\/\\/)?(www\\.)?[-a-zA-Z0-9@%._\\+~#=]{2,256}\\.[a-z]{2,6}\\b([-a-zA-Z0-9@:%_\\+.~#?&/=]*)$',
    )
    botName: str | None = Field(
        None,
        description='Display name the bot uses when it appears in the participant list.\nDefaults to a configured fallback when omitted.',
        max_length=100,
    )
    joinAt: str | None = Field(
        None,
        description='Scheduled join time. Must be within 10 minutes of a real meeting\nstart — Recall rejects bots scheduled too far out. Enforcement lives\nin the RecallClient (not Smithy-expressible).\nOmit for immediate dispatch.',
        pattern='^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d+([+-][0-2]\\d:[0-5]\\d|Z)$',
    )


class CreateMeetingBotResponseContent(BaseModel):
    botId: str = Field(
        ...,
        description='Recall.ai bot identifier. Externally assigned by Recall; we treat it as an\nopaque UUID-shaped string.',
        pattern='^[A-Za-z0-9-]+$',
    )
    status: str = Field(
        ...,
        description='Recall.ai bot lifecycle status. Raw string from the Recall API — we intentionally\ndo not model this as an enum because Recall owns the taxonomy and introduces new\nstates without a contract bump. Callers should branch on well-known values\n(`joining_call`, `in_call_recording`, `done`, `fatal`) and treat unknown values\nas transient.',
    )


class Email(RootModel[str]):
    root: str = Field(..., pattern='^[\\w-\\.]+@[\\w-\\.]+\\.+[\\w-]{1,63}$')


class CreateOrgInviteRequestContent(BaseModel):
    orgId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    emails: list[Email]
    role: str
    customRoleId: str | None = Field(None, pattern='^[A-Za-z0-9-]+$')
    orgEmail: str | None = Field(
        None, pattern='^[\\w-\\.]+@[\\w-\\.]+\\.+[\\w-]{1,63}$'
    )


class FailedEmail(RootModel[str]):
    root: str = Field(..., pattern='^[\\w-\\.]+@[\\w-\\.]+\\.+[\\w-]{1,63}$')


class CreateOrgRequestContent(BaseModel):
    name: str
    type: str
    description: str | None
    website: str | None = Field(
        None,
        pattern='^(https?:\\/\\/)?(www\\.)?[-a-zA-Z0-9@%._\\+~#=]{2,256}\\.[a-z]{2,6}\\b([-a-zA-Z0-9@:%_\\+.~#?&/=]*)$',
    )
    billingEmail: str = Field(..., pattern='^[\\w-\\.]+@[\\w-\\.]+\\.+[\\w-]{1,63}$')


class FileId(RootModel[str]):
    root: str = Field(..., description='File identifier', pattern='^[A-Za-z0-9-]+$')


class Deal(BaseModel):
    """
    Main deal entity
    """

    dealId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    ownerUserId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    ownerOrgId: str | None = Field(
        None,
        description='Organization context (nullable for personal deals)',
        pattern='^[A-Za-z0-9-]+$',
    )
    parentDealId: str | None = Field(
        None,
        description='Parent deal for hierarchies (master agreements, amendments)',
        pattern='^[A-Za-z0-9-]+$',
    )
    createdByUserId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    updatedByUserId: str | None = Field(None, pattern='^[A-Za-z0-9-]+$')
    fileIds: list[FileId] | None = Field(None, description='Associated file IDs')
    createdAt: str = Field(
        ...,
        pattern='^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d+([+-][0-2]\\d:[0-5]\\d|Z)$',
    )
    updatedAt: str = Field(
        ...,
        pattern='^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d+([+-][0-2]\\d:[0-5]\\d|Z)$',
    )


class DealMap(RootModel[dict[str, Deal]]):
    root: dict[str, Deal]


class DealPermission(StrEnum):
    """
    Deal permissions
    """

    view_deal = 'view_deal'
    edit_deal = 'edit_deal'
    delete_deal = 'delete_deal'
    manage_access = 'manage_access'
    approve_deal = 'approve_deal'
    create_version = 'create_version'
    view_ai_analysis = 'view_ai_analysis'
    view_revision_history = 'view_revision_history'
    export_deal = 'export_deal'
    manage_deliverables = 'manage_deliverables'
    comment_deal = 'comment_deal'
    view_financial = 'view_financial'
    edit_financial = 'edit_financial'


class DealStage(StrEnum):
    """
    Deal stage lifecycle
    """

    drafting = 'drafting'
    negotiation = 'negotiation'
    signing = 'signing'
    delivery = 'delivery'
    completed = 'completed'
    cancelled = 'cancelled'


class DealThreadAssociationType(StrEnum):
    """
    How a thread was associated with a deal
    """

    manual = 'manual'
    ai_suggested = 'ai_suggested'
    participant_match = 'participant_match'


class DealThreadStatus(StrEnum):
    """
    Suggestion workflow status for deal-thread associations
    """

    pending = 'pending'
    accepted = 'accepted'
    rejected = 'rejected'


class DealVersion(BaseModel):
    """
    Deal version for tracking changes through stages
    """

    dealVersionId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    dealId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    versionNumber: float
    stage: DealStage
    content: Any = Field(
        ...,
        description='Main deal content (name, description, terms, financial details)',
    )
    metadata: Any | None = Field(
        None, description='Metadata for extensibility during beta'
    )
    createdByUserId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    approvedByUserId: str | None = Field(
        None, description='Approval workflow tracking', pattern='^[A-Za-z0-9-]+$'
    )
    fileIds: list[FileId] | None = Field(None, description='Associated file IDs')
    createdAt: str = Field(
        ...,
        pattern='^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d+([+-][0-2]\\d:[0-5]\\d|Z)$',
    )
    approvedAt: str | None = Field(
        None,
        description='When this version was approved',
        pattern='^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d+([+-][0-2]\\d:[0-5]\\d|Z)$',
    )


class DealVersionMap(RootModel[dict[str, DealVersion]]):
    root: dict[str, DealVersion]


class DeclineOrgInviteRequestContent(BaseModel):
    orgId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    inviteId: str = Field(..., pattern='^[A-Za-z0-9-]+$')


class DeleteDealRequestContent(BaseModel):
    dealId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    hardDelete: bool | None = Field(None, description='Soft delete by default')


class DeleteDealThreadRequestContent(BaseModel):
    dealId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    dealThreadId: str = Field(..., pattern='^[A-Za-z0-9-]+$')


class DeleteDealThreadResponseContent(BaseModel):
    success: bool


class DeleteFileRequestContent(BaseModel):
    fileId: str = Field(..., description='File identifier', pattern='^[A-Za-z0-9-]+$')
    hardDelete: bool | None = Field(
        None, description='Hard delete the file (default is soft delete)'
    )


class DeleteOrgCustomRoleRequestContent(BaseModel):
    orgId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    customRoleId: str = Field(..., pattern='^[A-Za-z0-9-]+$')


class DeleteOrgRequestContent(BaseModel):
    orgId: str = Field(..., pattern='^[A-Za-z0-9-]+$')


class DeliverableSource(StrEnum):
    """
    Deliverable source (for tracking origin)
    """

    inferred = 'inferred'
    template = 'template'
    imported = 'imported'
    manual = 'manual'


class DeliverableStatus(StrEnum):
    incomplete = 'incomplete'
    in_progress = 'in_progress'
    overdue = 'overdue'
    complete = 'complete'


class EmailParticipant(BaseModel):
    """
    Email participant (sender/recipient)
    Matches Nylas v3 participant structure
    """

    email: str = Field(..., pattern='^[\\w-\\.]+@[\\w-\\.]+\\.+[\\w-]{1,63}$')
    name: str | None


class File(BaseModel):
    """
    File entity with dual-ownership pattern
    """

    fileId: str = Field(..., description='File identifier', pattern='^[A-Za-z0-9-]+$')
    ownerUserId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    ownerOrgId: str | None = Field(
        None,
        description='Organization context (nullable for personal files)',
        pattern='^[A-Za-z0-9-]+$',
    )
    createdByUserId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    fileName: str
    sizeBytes: float
    fileType: str
    description: str | None = Field(None, description='File description')
    dealIds: list[DealId] | None = Field(None, description='Associated deal IDs')
    dealVersionIds: list[DealVersionId] | None = Field(
        None, description='Associated deal version IDs'
    )
    metadata: Any | None = Field(None, description='Additional metadata as JSON')
    updatedByUserId: str | None = Field(None, pattern='^[A-Za-z0-9-]+$')
    createdAt: str = Field(
        ...,
        pattern='^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d+([+-][0-2]\\d:[0-5]\\d|Z)$',
    )
    updatedAt: str = Field(
        ...,
        pattern='^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d+([+-][0-2]\\d:[0-5]\\d|Z)$',
    )


class FileMap(RootModel[dict[str, File]]):
    root: dict[str, File]


class FilePermission(StrEnum):
    """
    File permissions
    """

    view_file = 'view_file'
    edit_file = 'edit_file'
    delete_file = 'delete_file'
    share_file = 'share_file'
    manage_access = 'manage_access'
    comment_file = 'comment_file'
    export_file = 'export_file'
    rename_file = 'rename_file'


class GenerateDownloadUrlRequestContent(BaseModel):
    fileId: str = Field(..., description='File identifier', pattern='^[A-Za-z0-9-]+$')
    expirationSeconds: float | None = Field(
        None, description='Expiration time in seconds (default 3600)'
    )
    disposition: ContentDisposition | None
    downloadFileName: str | None = Field(
        None, description='Override filename in download'
    )


class GenerateUploadUrlRequestContent(BaseModel):
    fileId: str = Field(..., description='File identifier', pattern='^[A-Za-z0-9-]+$')
    contentType: str | None = Field(None, description='Content type for the upload')
    expirationSeconds: float | None = Field(
        None, description='Expiration time in seconds (default 3600)'
    )


class GetAuditLogRequestContent(BaseModel):
    auditLogId: str = Field(
        ..., description='Audit log identifier', pattern='^[A-Za-z0-9-]+$'
    )


class GetDealRequestContent(BaseModel):
    dealId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    includeVersions: bool | None = Field(None, description='Include related data')
    includeDeliverables: bool | None
    includeAccess: bool | None


class GetDealVersionRequestContent(BaseModel):
    dealId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    dealVersionId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    includeDeliverables: bool | None = Field(
        None, description='Include deliverables for this version'
    )


class GetFileRequestContent(BaseModel):
    fileId: str = Field(..., description='File identifier', pattern='^[A-Za-z0-9-]+$')
    includeAccess: bool | None = Field(None, description='Include access information')
    requestDownloadUrl: bool | None = Field(
        None, description='Request download URL in response'
    )


class GetMeetingBotStatusRequestContent(BaseModel):
    botId: str = Field(
        ...,
        description='Recall.ai bot identifier. Externally assigned by Recall; we treat it as an\nopaque UUID-shaped string.',
        pattern='^[A-Za-z0-9-]+$',
    )


class GetMeetingBotStatusResponseContent(BaseModel):
    status: str = Field(
        ...,
        description='Recall.ai bot lifecycle status. Raw string from the Recall API — we intentionally\ndo not model this as an enum because Recall owns the taxonomy and introduces new\nstates without a contract bump. Callers should branch on well-known values\n(`joining_call`, `in_call_recording`, `done`, `fatal`) and treat unknown values\nas transient.',
    )
    recordingUrl: str | None = Field(
        None,
        description='Presigned URL to the raw video/audio recording, if Recall has\nfinished upload. Clients should treat absence as "not ready yet."',
        pattern='^(https?:\\/\\/)?(www\\.)?[-a-zA-Z0-9@%._\\+~#=]{2,256}\\.[a-z]{2,6}\\b([-a-zA-Z0-9@:%_\\+.~#?&/=]*)$',
    )
    transcriptAvailable: bool | None = Field(
        None,
        description='True when the transcript download has completed and\n`GetMeetingTranscript` will return content.',
    )


class GetMeetingRecordingRequestContent(BaseModel):
    botId: str = Field(
        ...,
        description='Recall.ai bot identifier. Externally assigned by Recall; we treat it as an\nopaque UUID-shaped string.',
        pattern='^[A-Za-z0-9-]+$',
    )


class GetMeetingRecordingResponseContent(BaseModel):
    recordingUrl: str | None = Field(
        None,
        description='Presigned recording URL. Absent while upload is still processing.',
        pattern='^(https?:\\/\\/)?(www\\.)?[-a-zA-Z0-9@%._\\+~#=]{2,256}\\.[a-z]{2,6}\\b([-a-zA-Z0-9@:%_\\+.~#?&/=]*)$',
    )


class GetMeetingTranscriptRequestContent(BaseModel):
    botId: str = Field(
        ...,
        description='Recall.ai bot identifier. Externally assigned by Recall; we treat it as an\nopaque UUID-shaped string.',
        pattern='^[A-Za-z0-9-]+$',
    )


class GetOrgPictureRequestContent(BaseModel):
    orgId: str = Field(..., pattern='^[A-Za-z0-9-]+$')


class GetOrgPictureResponseContent(BaseModel):
    profilePictureURL: str = Field(
        ...,
        pattern='^(https?:\\/\\/)?(www\\.)?[-a-zA-Z0-9@%._\\+~#=]{2,256}\\.[a-z]{2,6}\\b([-a-zA-Z0-9@:%_\\+.~#?&/=]*)$',
    )


class GetOrgRequestContent(BaseModel):
    orgId: str = Field(..., pattern='^[A-Za-z0-9-]+$')


class GetOrgThemeRequestContent(BaseModel):
    orgId: str = Field(..., pattern='^[A-Za-z0-9-]+$')


class GetProfilePictureRequestContent(BaseModel):
    userId: str = Field(..., pattern='^[A-Za-z0-9-]+$')


class GetProfilePictureResponseContent(BaseModel):
    profilePictureURL: str = Field(
        ...,
        pattern='^(https?:\\/\\/)?(www\\.)?[-a-zA-Z0-9@%._\\+~#=]{2,256}\\.[a-z]{2,6}\\b([-a-zA-Z0-9@:%_\\+.~#?&/=]*)$',
    )


class GetProfileRequestContent(BaseModel):
    userId: str | None = Field(None, pattern='^[A-Za-z0-9-]+$')


class GrantDealAccessRequestContent(BaseModel):
    dealId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    grantToOrgId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    grantToUserId: str | None = Field(
        None,
        description='Specific user within org (if omitted, entire org has access)',
        pattern='^[A-Za-z0-9-]+$',
    )
    permissions: list[DealPermission]
    partyRole: str | None = Field(None, description='Optional party role')
    expiresAt: str | None = Field(
        None,
        description='Optional expiration',
        pattern='^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d+([+-][0-2]\\d:[0-5]\\d|Z)$',
    )
    grantablePermissions: list[DealPermission] | None = Field(
        None, description='Permissions they can grant to others'
    )
    isDeny: bool | None = Field(None, description='Explicit deny')


class GrantFileAccessRequestContent(BaseModel):
    fileId: str = Field(..., description='File identifier', pattern='^[A-Za-z0-9-]+$')
    grantToOrgId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    grantToUserId: str | None = Field(
        None,
        description='Specific user within org (if omitted, entire org has access)',
        pattern='^[A-Za-z0-9-]+$',
    )
    permissions: list[FilePermission]
    expiresAt: str | None = Field(
        None,
        description='Optional expiration',
        pattern='^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d+([+-][0-2]\\d:[0-5]\\d|Z)$',
    )
    grantablePermissions: list[FilePermission] | None = Field(
        None, description='Permissions they can grant to others'
    )
    isDeny: bool | None = Field(None, description='Explicit deny')


class InternalServerErrorResponseContent(BaseModel):
    message: str


class InviteStatus(StrEnum):
    pending = 'pending'
    accepted = 'accepted'
    declined = 'declined'
    expired = 'expired'


class LeaveMeetingBotRequestContent(BaseModel):
    botId: str = Field(
        ...,
        description='Recall.ai bot identifier. Externally assigned by Recall; we treat it as an\nopaque UUID-shaped string.',
        pattern='^[A-Za-z0-9-]+$',
    )


class LeaveMeetingBotResponseContent(BaseModel):
    success: bool


class ListDealAccessRequestContent(BaseModel):
    dealId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    orgId: str | None = Field(
        None, description='Filter by organization', pattern='^[A-Za-z0-9-]+$'
    )
    includeRevoked: bool | None = Field(None, description='Include revoked access')
    includeExpired: bool | None = Field(None, description='Include expired access')
    nextToken: str | None = Field(
        None, description='Pagination cursor (encoded accessId)'
    )
    limit: float | None = Field(None, description='Page size', ge=1.0, le=100.0)


class ListDealThreadsRequestContent(BaseModel):
    dealId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    associationType: DealThreadAssociationType | None
    nextToken: str | None = Field(
        None, description='Pagination cursor (encoded dealThreadId)'
    )
    limit: float | None = Field(None, description='Page size', ge=1.0, le=100.0)


class ListDealVersionsRequestContent(BaseModel):
    dealId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    stage: DealStage | None
    nextToken: str | None = Field(
        None, description='Pagination cursor (encoded versionId)'
    )
    limit: float | None = Field(None, description='Page size', ge=1.0, le=100.0)


class ListDealVersionsResponseContent(BaseModel):
    versions: DealVersionMap
    nextToken: str | None = Field(None, description='Token for next page')


class ListDealsRequestContent(BaseModel):
    orgId: str | None = Field(
        None, description='Filter by organization', pattern='^[A-Za-z0-9-]+$'
    )
    stage: DealStage | None
    createdBy: str | None = Field(None, description='Filter by creator')
    nextToken: str | None = Field(
        None, description='Pagination cursor (encoded dealId)'
    )
    limit: float | None = Field(
        None, description='Page size (default 20, max 100)', ge=1.0, le=100.0
    )


class ListDealsResponseContent(BaseModel):
    deals: DealMap
    nextToken: str | None = Field(
        None, description='Token for next page (null if no more results)'
    )


class ListDeliverablesRequestContent(BaseModel):
    dealId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    dealVersionId: str | None = Field(
        None, description='Filter by version', pattern='^[A-Za-z0-9-]+$'
    )
    status: str | None = Field(None, description='Filter by status')
    assignedTo: str | None = Field(None, description='Filter by assignee')
    nextToken: str | None = Field(
        None, description='Pagination cursor (encoded deliverableId)'
    )
    limit: float | None = Field(None, description='Page size', ge=1.0, le=100.0)


class ListFileAccessRequestContent(BaseModel):
    fileId: str = Field(..., description='File identifier', pattern='^[A-Za-z0-9-]+$')
    orgId: str | None = Field(
        None, description='Filter by organization', pattern='^[A-Za-z0-9-]+$'
    )
    includeRevoked: bool | None = Field(None, description='Include revoked access')
    includeExpired: bool | None = Field(None, description='Include expired access')
    nextToken: str | None = Field(
        None, description='Pagination cursor (encoded accessId)'
    )
    limit: float | None = Field(None, description='Page size', ge=1.0, le=100.0)


class ListFilesRequestContent(BaseModel):
    orgId: str | None = Field(
        None, description='Filter by organization', pattern='^[A-Za-z0-9-]+$'
    )
    dealId: str | None = Field(
        None, description='Filter by deal', pattern='^[A-Za-z0-9-]+$'
    )
    dealVersionId: str | None = Field(
        None, description='Filter by deal version', pattern='^[A-Za-z0-9-]+$'
    )
    folderPath: str | None = Field(None, description='Filter by folder path')
    tags: list[Tag] | None = Field(None, description='Filter by tags (any match)')
    uploadedBy: str | None = Field(None, description='Filter by uploader')
    includeDeleted: bool | None = Field(None, description='Include deleted files')
    nextToken: str | None = Field(
        None, description='Pagination cursor (encoded fileId)'
    )
    limit: float | None = Field(None, ge=1.0, le=100.0)


class ListFilesResponseContent(BaseModel):
    files: FileMap
    nextToken: str | None = Field(None, description='Token for next page')
    totalSizeBytes: float | None = Field(
        None, description='Total size of files in current page'
    )


class ListMeetingBotsRequestContent(BaseModel):
    status: str | None = Field(
        None,
        description='Filter by Recall status string. Same taxonomy as the `status` field\non `MeetingBotSummary` — caller-chosen, not validated against an enum.',
    )
    limit: float | None = Field(
        None,
        description='Result limit. Default and max enforced by `PageLimit` (1..100).',
        ge=1.0,
        le=100.0,
    )


class ListOrgCustomRolesRequestContent(BaseModel):
    orgId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    nextToken: str | None = Field(
        None, description='Pagination cursor (encoded roleId)'
    )
    limit: float | None = Field(None, description='Page size', ge=1.0, le=100.0)


class ListOrgInvitesRequestContent(BaseModel):
    orgId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    status: InviteStatus | None
    nextToken: str | None = Field(
        None, description='Pagination cursor (encoded inviteId)'
    )
    limit: float | None = Field(None, description='Page size', ge=1.0, le=100.0)


class ListUserOrganizationsRequestContent(BaseModel):
    nextToken: str | None = Field(None, description='Pagination cursor (encoded orgId)')
    limit: float | None = Field(None, description='Page size', ge=1.0, le=100.0)


class MeetingBotSummary(BaseModel):
    """
    Summary of a meeting bot for list operations.
    Subset of GetMeetingBotStatus output — does NOT include recordingUrl or
    transcriptAvailable (those require per-bot Recall fetches that would blow
    up list latency).
    """

    botId: str = Field(
        ...,
        description='Recall.ai bot identifier. Externally assigned by Recall; we treat it as an\nopaque UUID-shaped string.',
        pattern='^[A-Za-z0-9-]+$',
    )
    meetingUrl: str = Field(
        ...,
        description='Meeting platform URL the bot joined (Zoom / Meet / Teams link).',
        pattern='^(https?:\\/\\/)?(www\\.)?[-a-zA-Z0-9@%._\\+~#=]{2,256}\\.[a-z]{2,6}\\b([-a-zA-Z0-9@:%_\\+.~#?&/=]*)$',
    )
    status: str = Field(
        ...,
        description='Recall.ai bot lifecycle status. Raw string from the Recall API — we intentionally\ndo not model this as an enum because Recall owns the taxonomy and introduces new\nstates without a contract bump. Callers should branch on well-known values\n(`joining_call`, `in_call_recording`, `done`, `fatal`) and treat unknown values\nas transient.',
    )
    botName: str | None = Field(
        None, description='Display name the bot uses when it joins the call.'
    )
    joinAt: str | None = Field(
        None,
        description='Scheduled join time. Absent when the bot was dispatched immediately.',
        pattern='^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d+([+-][0-2]\\d:[0-5]\\d|Z)$',
    )
    createdAt: str = Field(
        ...,
        pattern='^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d+([+-][0-2]\\d:[0-5]\\d|Z)$',
    )


class NylasConnection(BaseModel):
    """
    Nylas connection status
    Note: grantId intentionally excluded - internal Nylas credential, not for frontend
    """

    connectionId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    email: str = Field(..., pattern='^[\\w-\\.]+@[\\w-\\.]+\\.+[\\w-]{1,63}$')
    provider: str = Field(
        ..., description="Email provider: 'google', 'microsoft', etc."
    )
    enabled: bool
    connectedAt: str = Field(
        ...,
        pattern='^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d+([+-][0-2]\\d:[0-5]\\d|Z)$',
    )
    scopes: list[str] | None = Field(None, description='OAuth scopes granted')


class NylasDisconnectConnectionRequestContent(BaseModel):
    connectionId: str = Field(
        ...,
        description='Connection ID to disconnect (required for multi-account)',
        pattern='^[A-Za-z0-9-]+$',
    )


class NylasDisconnectConnectionResponseContent(BaseModel):
    success: bool


class NylasGetMessageRequestContent(BaseModel):
    connectionId: str = Field(
        ...,
        description='Connection ID to use for this request',
        pattern='^[A-Za-z0-9-]+$',
    )
    messageId: str


class NylasGetThreadRequestContent(BaseModel):
    threadMetadataId: str = Field(
        ..., description='Thread metadata ID', pattern='^[A-Za-z0-9-]+$'
    )


class NylasInitiateAuthRequestContent(BaseModel):
    provider: str | None = Field(
        None, description='Optional: Specify email provider hint'
    )
    orgId: str | None = Field(
        None,
        description='Organization context - which org this email connection belongs to\nIncluded in JWT state and stored on the connection after callback',
        pattern='^[A-Za-z0-9-]+$',
    )


class NylasInitiateAuthResponseContent(BaseModel):
    authUrl: str = Field(
        ...,
        pattern='^(https?:\\/\\/)?(www\\.)?[-a-zA-Z0-9@%._\\+~#=]{2,256}\\.[a-z]{2,6}\\b([-a-zA-Z0-9@:%_\\+.~#?&/=]*)$',
    )
    state: str = Field(..., description='State parameter for CSRF validation')


class NylasListConnectionsResponseContent(BaseModel):
    connected: bool
    connections: list[NylasConnection] | None = Field(
        None, description='List of active connections'
    )


class NylasListMessagesRequestContent(BaseModel):
    connectionId: str = Field(
        ...,
        description='Connection ID to use for this request',
        pattern='^[A-Za-z0-9-]+$',
    )
    limit: float | None = Field(
        None,
        description='Maximum number of messages to return (default 50, max 200)',
        ge=1.0,
        le=200.0,
    )
    cursor: str | None = Field(
        None, description='Pagination cursor from previous response'
    )
    subject: str | None = Field(None, description='Filter by subject')
    anyEmail: str | None = Field(
        None,
        description='Filter by sender email',
        pattern='^[\\w-\\.]+@[\\w-\\.]+\\.+[\\w-]{1,63}$',
    )
    in_: str | None = Field(None, alias='in', description='Filter to folder/label')
    unread: bool | None = Field(None, description='Filter unread messages')
    starred: bool | None = Field(None, description='Filter starred messages')
    receivedAfter: float | None = Field(
        None, description='Unix timestamp - messages after this date'
    )
    receivedBefore: float | None = Field(
        None, description='Unix timestamp - messages before this date'
    )


class NylasListThreadsRequestContent(BaseModel):
    connectionId: str = Field(
        ...,
        description='Connection ID to use for this request',
        pattern='^[A-Za-z0-9-]+$',
    )
    minPriority: float | None = Field(
        None, description='Filter by priority (minimum value)'
    )
    label: str | None = Field(None, description='Filter by label')
    analyzedOnly: bool | None = Field(None, description='Filter analyzed threads only')
    nextToken: str | None = Field(
        None, description='Pagination cursor (encoded threadMetadataId)'
    )
    limit: float | None = Field(None, description='Page size', ge=1.0, le=100.0)


class NylasMessage(BaseModel):
    """
    Email message
    Matches Nylas v3 Message object structure
    """

    id: str = Field(..., description='Nylas message ID')
    threadId: str | None = Field(None, description='Thread ID')
    subject: str
    snippet: str | None = Field(None, description='Plain text preview/snippet')
    body: str | None = Field(None, description='Email body (HTML or plain text)')
    from_: list[EmailParticipant] | None = Field(
        None, alias='from', description='Sender information'
    )
    to: list[EmailParticipant] | None = Field(None, description='Recipients')
    cc: list[EmailParticipant] | None
    bcc: list[EmailParticipant] | None
    replyTo: list[EmailParticipant] | None
    date: float = Field(..., description='Unix timestamp (seconds)')
    unread: bool
    starred: bool | None
    folders: list[str] | None = Field(None, description='Folder names/labels')


class NylasSendMessageRequestContent(BaseModel):
    connectionId: str = Field(
        ...,
        description='Connection ID to use for this request',
        pattern='^[A-Za-z0-9-]+$',
    )
    to: list[EmailParticipant]
    cc: list[EmailParticipant] | None
    bcc: list[EmailParticipant] | None
    replyTo: list[EmailParticipant] | None
    subject: str
    body: str = Field(..., description='Email body (HTML or plain text)')
    replyToMessageId: str | None = Field(
        None, description='Reply to specific message (for threading)'
    )


class NylasSendMessageResponseContent(BaseModel):
    requestId: str
    data: NylasMessage


class NylasThread(BaseModel):
    """
    Thread with enriched metadata
    """

    threadMetadataId: str = Field(
        ..., description='Our database ID', pattern='^[A-Za-z0-9-]+$'
    )
    externalThreadId: str = Field(..., description='Nylas thread ID')
    provider: str
    connectionEmail: str | None = Field(
        None, description='Email address of the connected account'
    )
    lastMessageAt: str = Field(
        ...,
        description='Timeline',
        pattern='^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d+([+-][0-2]\\d:[0-5]\\d|Z)$',
    )
    messageCount: float
    summary: str | None = Field(None, description='AI-generated metadata (no PII)')
    priority: float | None
    labels: list[str] | None
    ragKeywords: list[str] | None
    analyzed: bool = Field(..., description='Processing state')
    analyzedAt: str | None = Field(
        None,
        pattern='^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d+([+-][0-2]\\d:[0-5]\\d|Z)$',
    )
    createdAt: str = Field(
        ...,
        pattern='^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d+([+-][0-2]\\d:[0-5]\\d|Z)$',
    )
    updatedAt: str = Field(
        ...,
        pattern='^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d+([+-][0-2]\\d:[0-5]\\d|Z)$',
    )


class Org(BaseModel):
    orgId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    name: str
    type: str
    primaryOwnerId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    description: str | None
    website: str | None = Field(
        None,
        pattern='^(https?:\\/\\/)?(www\\.)?[-a-zA-Z0-9@%._\\+~#=]{2,256}\\.[a-z]{2,6}\\b([-a-zA-Z0-9@:%_\\+.~#?&/=]*)$',
    )
    logoUrl: str | None = Field(
        None,
        pattern='^(https?:\\/\\/)?(www\\.)?[-a-zA-Z0-9@%._\\+~#=]{2,256}\\.[a-z]{2,6}\\b([-a-zA-Z0-9@:%_\\+.~#?&/=]*)$',
    )
    billingEmail: str | None = Field(
        None, pattern='^[\\w-\\.]+@[\\w-\\.]+\\.+[\\w-]{1,63}$'
    )
    metadata: Any | None = Field(
        None,
        description='Additional metadata (UI preferences, etc.)\nTODO: Post-beta - Consider removing if unused or replace with explicit typed fields',
    )
    createdAt: str = Field(
        ...,
        pattern='^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d+([+-][0-2]\\d:[0-5]\\d|Z)$',
    )
    updatedAt: str = Field(
        ...,
        pattern='^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d+([+-][0-2]\\d:[0-5]\\d|Z)$',
    )
    memberCount: float | None
    userRole: str | None
    dealCount: float | None
    inviteCount: float | None
    roleCount: float | None


class OrgMap(RootModel[dict[str, Org]]):
    root: dict[str, Org]


class OrgMemberFilter(StrEnum):
    active = 'active'
    inactive = 'inactive'


class OrgPermission(StrEnum):
    """
    Organization permissions
    """

    manage_members = 'manage_members'
    manage_billing = 'manage_billing'
    manage_settings = 'manage_settings'
    invite_users = 'invite_users'
    manage_roles = 'manage_roles'
    view_analytics = 'view_analytics'
    view_audit_logs = 'view_audit_logs'
    view_all_deals = 'view_all_deals'
    view_all_files = 'view_all_files'


class OrgTheme(BaseModel):
    primaryColor: str | None = Field(
        None, pattern='^#?([0-9a-fA-F]{6}|[0-9a-fA-F]{3})$'
    )
    secondaryColor: str | None = Field(
        None, pattern='^#?([0-9a-fA-F]{6}|[0-9a-fA-F]{3})$'
    )
    accentColor: str | None = Field(None, pattern='^#?([0-9a-fA-F]{6}|[0-9a-fA-F]{3})$')


class PingResponseContent(BaseModel):
    message: str


class PresignedPostData(BaseModel):
    """
    Common types and structures shared across all operations
    """

    url: str = Field(
        ...,
        pattern='^(https?:\\/\\/)?(www\\.)?[-a-zA-Z0-9@%._\\+~#=]{2,256}\\.[a-z]{2,6}\\b([-a-zA-Z0-9@:%_\\+.~#?&/=]*)$',
    )
    fields: Any


class PresignedUrl(BaseModel):
    """
    Presigned URL response
    """

    url: str = Field(
        ...,
        pattern='^(https?:\\/\\/)?(www\\.)?[-a-zA-Z0-9@%._\\+~#=]{2,256}\\.[a-z]{2,6}\\b([-a-zA-Z0-9@:%_\\+.~#?&/=]*)$',
    )
    expiresAt: str = Field(
        ...,
        pattern='^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d+([+-][0-2]\\d:[0-5]\\d|Z)$',
    )
    method: str | None = Field(None, description='HTTP method for the URL')
    headers: Any | None = Field(None, description='Required headers for the request')


class RecordType(StrEnum):
    """
    Record types for audit log entries
    """

    normal = 'normal'
    meta_audit = 'meta_audit'
    unknown = 'unknown'
    cleanup = 'cleanup'
    export = 'export'
    system = 'system'


class RemoveOrgMemberRequestContent(BaseModel):
    orgId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    userId: str = Field(..., pattern='^[A-Za-z0-9-]+$')


class ResendOrgInviteRequestContent(BaseModel):
    orgId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    inviteId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    expiresDate: str | None = Field(
        None,
        pattern='^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d+([+-][0-2]\\d:[0-5]\\d|Z)$',
    )


class ResourceNotFoundErrorResponseContent(BaseModel):
    message: str


class RevokeDealAccessRequestContent(BaseModel):
    dealId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    accessId: str = Field(
        ..., description='Access control identifier', pattern='^[A-Za-z0-9-]+$'
    )
    reason: str


class RevokeFileAccessRequestContent(BaseModel):
    fileId: str = Field(..., description='File identifier', pattern='^[A-Za-z0-9-]+$')
    accessId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    reason: str


class StatisticGrouping(StrEnum):
    """
    Statistic grouping periods
    """

    hour = 'hour'
    day = 'day'
    week = 'week'
    month = 'month'


class TimeSeriesPoint(BaseModel):
    """
    Time series data point
    """

    timestamp: str = Field(
        ...,
        pattern='^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d+([+-][0-2]\\d:[0-5]\\d|Z)$',
    )
    count: float
    metrics: Any | None = Field(None, description='Additional metrics')


class TranscriptParticipant(BaseModel):
    """
    Speaker identity attached to a TranscriptParticipantEntry.
    `id` is Recall's participant identifier (scoped to the call, not globally
    unique); `name` is the display name Recall captured from the platform.
    """

    id: float = Field(
        ...,
        description='Recall-assigned participant ID (small integer, scoped to the call).',
    )
    name: str
    isHost: bool = Field(
        ..., description='True when this participant owns / hosts the meeting.'
    )
    platform: str = Field(
        ...,
        description='Meeting platform the participant joined from (e.g. `zoom`, `meet`, `teams`).',
    )
    extraData: Any | None = Field(
        None,
        description='Free-form platform metadata passed through from Recall. Shape varies per\nplatform; treat as opaque JSON.',
    )


class TranscriptTimestamp(BaseModel):
    """
    Timestamp pair: `relative` is seconds from the start of the recording
    (useful for playback offsets); `absolute` is the wall-clock ISO8601 time.
    """

    relative: float
    absolute: str = Field(
        ...,
        pattern='^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d+([+-][0-2]\\d:[0-5]\\d|Z)$',
    )


class TranscriptWord(BaseModel):
    """
    One transcribed word with precise start/end timestamps.
    """

    text: str
    startTimestamp: TranscriptTimestamp
    endTimestamp: TranscriptTimestamp


class TransferOrgOwnershipRequestContent(BaseModel):
    orgId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    newOwnerId: str = Field(..., pattern='^[A-Za-z0-9-]+$')


class TransferOrgOwnershipResponseContent(BaseModel):
    org: Org


class UpdateDealAccessRequestContent(BaseModel):
    dealId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    accessId: str = Field(
        ..., description='Access control identifier', pattern='^[A-Za-z0-9-]+$'
    )
    permissions: list[DealPermission] | None
    grantablePermissions: list[DealPermission] | None
    partyRole: str | None
    expiresAt: str | None = Field(
        None,
        pattern='^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d+([+-][0-2]\\d:[0-5]\\d|Z)$',
    )
    isDeny: bool | None


class UpdateDealRequestContent(BaseModel):
    dealId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    title: str | None
    description: str | None
    newStage: DealStage | None
    changeReason: str | None = Field(None, description='Required when changing stage')
    metadata: Any | None = Field(None, description='Optional metadata for new version')


class UpdateDealResponseContent(BaseModel):
    deal: Deal
    newVersion: DealVersion | None


class UpdateDealThreadRequestContent(BaseModel):
    dealId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    dealThreadId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    status: DealThreadStatus | None
    notes: str | None = Field(None, description='Updated notes')


class UpdateDeliverableRequestContent(BaseModel):
    dealId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    deliverableId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    description: str | None
    source: DeliverableSource | None
    dueDate: str | None = Field(
        None,
        pattern='^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d+([+-][0-2]\\d:[0-5]\\d|Z)$',
    )
    assignedTo: str | None
    status: str | None


class UpdateFileAccessRequestContent(BaseModel):
    fileId: str = Field(..., description='File identifier', pattern='^[A-Za-z0-9-]+$')
    accessId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    permissions: list[FilePermission] | None
    grantablePermissions: list[FilePermission] | None
    expiresAt: str | None = Field(
        None,
        pattern='^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d+([+-][0-2]\\d:[0-5]\\d|Z)$',
    )
    isDeny: bool | None


class UpdateFileRequestContent(BaseModel):
    fileId: str = Field(..., description='File identifier', pattern='^[A-Za-z0-9-]+$')
    fileName: str | None
    folderPath: str | None
    tags: list[Tag] | None
    dealIds: list[DealId] | None = Field(None, description='List of deal identifiers')
    dealVersionIds: list[DealVersionId] | None = Field(
        None, description='List of deal version identifiers'
    )


class UpdateFileResponseContent(BaseModel):
    file: File


class UpdateOrgCustomRoleRequestContent(BaseModel):
    orgId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    customRoleId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    name: str | None
    description: str | None
    permissions: list[OrgPermission] | None


class UpdateOrgMemberRequestContent(BaseModel):
    orgId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    userId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    role: str | None
    customRoleId: str | None = Field(None, pattern='^[A-Za-z0-9-]+$')
    orgEmail: str | None = Field(
        None, pattern='^[\\w-\\.]+@[\\w-\\.]+\\.+[\\w-]{1,63}$'
    )


class UpdateOrgRequestContent(BaseModel):
    orgId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    name: str | None
    description: str | None
    website: str | None = Field(
        None,
        pattern='^(https?:\\/\\/)?(www\\.)?[-a-zA-Z0-9@%._\\+~#=]{2,256}\\.[a-z]{2,6}\\b([-a-zA-Z0-9@:%_\\+.~#?&/=]*)$',
    )
    billingEmail: str | None = Field(
        None, pattern='^[\\w-\\.]+@[\\w-\\.]+\\.+[\\w-]{1,63}$'
    )


class UpdateOrgResponseContent(BaseModel):
    org: Org


class UpdateOrgThemeRequestContent(BaseModel):
    orgId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    theme: OrgTheme


class UpdateOrgThemeResponseContent(BaseModel):
    theme: OrgTheme


class UpdateProfileRequestContent(BaseModel):
    firstName: str | None
    lastName: str | None
    displayName: str | None
    accountType: str | None
    bio: str | None
    isOver18: bool | None


class UploadOrgPictureRequestContent(BaseModel):
    orgId: str = Field(..., pattern='^[A-Za-z0-9-]+$')


class UploadOrgPictureResponseContent(BaseModel):
    urlInfo: PresignedPostData


class UploadProfilePictureResponseContent(BaseModel):
    urlInfo: PresignedPostData


class UserProfile(BaseModel):
    userId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    firstName: str
    lastName: str
    displayName: str | None
    email: str = Field(..., pattern='^[\\w-\\.]+@[\\w-\\.]+\\.+[\\w-]{1,63}$')
    accountType: str | None
    bio: str | None


class ValidationErrorResponseContent(BaseModel):
    message: str


class AuditLog(BaseModel):
    """
    Audit log entry for field-level change tracking
    """

    auditLogId: str = Field(
        ..., description='Audit log identifier', pattern='^[A-Za-z0-9-]+$'
    )
    tableName: str
    recordType: RecordType
    operation: AuditOperation
    fieldName: str | None = Field(
        None, description='Specific field that changed (for UPDATE operations)'
    )
    oldValue: Any | None = Field(None, description='Previous value (JSON)')
    newValue: Any | None = Field(None, description='New value (JSON)')
    changedBy: str
    changedAt: str = Field(
        ...,
        pattern='^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d+([+-][0-2]\\d:[0-5]\\d|Z)$',
    )
    metadata: Any | None = Field(
        None, description='Additional metadata for extensibility'
    )


class AuditLogMap(RootModel[dict[str, AuditLog]]):
    root: dict[str, AuditLog]


class CreateDealRequestContent(BaseModel):
    orgId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    title: str
    description: str | None
    initialStage: DealStage | None
    metadata: Any | None = Field(
        None, description='Optional metadata for the initial version'
    )


class CreateDealResponseContent(BaseModel):
    deal: Deal
    initialVersion: DealVersion


class CreateDealThreadRequestContent(BaseModel):
    dealId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    threadMetadataId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    associationType: DealThreadAssociationType
    notes: str | None


class CreateDealVersionRequestContent(BaseModel):
    dealId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    stage: DealStage
    changeReason: str
    metadata: Any | None = Field(None, description='Optional metadata for version')


class CreateDealVersionResponseContent(BaseModel):
    version: DealVersion


class CreateDeliverableRequestContent(BaseModel):
    dealId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    dealVersionId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    description: str
    source: DeliverableSource | None
    dueDate: str | None = Field(
        None,
        description='For committed stages',
        pattern='^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d+([+-][0-2]\\d:[0-5]\\d|Z)$',
    )
    assignedTo: str | None
    status: str | None


class CreateFileResponseContent(BaseModel):
    file: File
    uploadUrl: PresignedUrl | None


class CreateOrgCustomRoleRequestContent(BaseModel):
    orgId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    name: str
    description: str | None
    permissions: list[OrgPermission]


class CreateOrgResponseContent(BaseModel):
    org: Org


class DealAccess(BaseModel):
    """
    Deal access control
    """

    dealAccessId: str = Field(
        ..., description='Access control identifier', pattern='^[A-Za-z0-9-]+$'
    )
    dealId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    grantedToOrgId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    grantedToUserId: str | None = Field(
        None,
        description='Specific user within org (if omitted, entire org has access)',
        pattern='^[A-Za-z0-9-]+$',
    )
    grantedByUserId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    grantedAt: str = Field(
        ...,
        pattern='^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d+([+-][0-2]\\d:[0-5]\\d|Z)$',
    )
    expiresAt: str | None = Field(
        None,
        description='Optional expiration',
        pattern='^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d+([+-][0-2]\\d:[0-5]\\d|Z)$',
    )
    partyRole: str | None = Field(
        None, description='Party role (e.g., "buyer", "seller", "advisor")'
    )
    permissions: list[DealPermission]
    grantablePermissions: list[DealPermission] | None = Field(
        None, description='Maximum permissions this party can grant to others'
    )
    isDeny: bool | None = Field(
        None, description='Explicit deny (overrides all grants)'
    )
    revokedByUserId: str | None = Field(
        None, description='Revocation tracking', pattern='^[A-Za-z0-9-]+$'
    )
    revokedAt: str | None = Field(
        None,
        pattern='^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d+([+-][0-2]\\d:[0-5]\\d|Z)$',
    )
    revocationReason: str | None
    metadata: Any | None = Field(
        None,
        description='Additional metadata as JSON\nTODO: Post-beta - Consider removing if unused or replace with explicit typed fields',
    )
    createdAt: str = Field(
        ...,
        pattern='^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d+([+-][0-2]\\d:[0-5]\\d|Z)$',
    )
    updatedAt: str = Field(
        ...,
        pattern='^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d+([+-][0-2]\\d:[0-5]\\d|Z)$',
    )


class DealAccessMap(RootModel[dict[str, DealAccess]]):
    root: dict[str, DealAccess]


class DealThread(BaseModel):
    """
    Deal-Thread association
    """

    dealThreadId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    dealId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    threadMetadataId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    associationType: DealThreadAssociationType
    status: DealThreadStatus
    associatedBy: str | None = Field(None, pattern='^[A-Za-z0-9-]+$')
    associatedAt: str | None = Field(
        None,
        pattern='^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d+([+-][0-2]\\d:[0-5]\\d|Z)$',
    )
    notes: str | None
    createdAt: str = Field(
        ...,
        pattern='^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d+([+-][0-2]\\d:[0-5]\\d|Z)$',
    )
    updatedAt: str = Field(
        ...,
        pattern='^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d+([+-][0-2]\\d:[0-5]\\d|Z)$',
    )


class DealThreadMap(RootModel[dict[str, DealThread]]):
    root: dict[str, DealThread]


class Deliverable(BaseModel):
    """
    Deliverable with stage-conditional fields
    """

    deliverableId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    dealVersionId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    name: str
    description: str | None
    source: DeliverableSource | None
    status: DeliverableStatus | None
    assignedToUserId: str | None = Field(None, pattern='^[A-Za-z0-9-]+$')
    responsibleOrgId: str | None = Field(None, pattern='^[A-Za-z0-9-]+$')
    dueDate: str | None = Field(
        None,
        pattern='^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d+([+-][0-2]\\d:[0-5]\\d|Z)$',
    )
    completedDate: str | None = Field(
        None,
        pattern='^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d+([+-][0-2]\\d:[0-5]\\d|Z)$',
    )
    metadata: Any | None
    createdByUserId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    updatedByUserId: str | None = Field(None, pattern='^[A-Za-z0-9-]+$')
    createdAt: str = Field(
        ...,
        pattern='^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d+([+-][0-2]\\d:[0-5]\\d|Z)$',
    )
    updatedAt: str = Field(
        ...,
        pattern='^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d+([+-][0-2]\\d:[0-5]\\d|Z)$',
    )


class DeliverableMap(RootModel[dict[str, Deliverable]]):
    root: dict[str, Deliverable]


class FileAccess(BaseModel):
    """
    File access control
    """

    fileAccessId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    fileId: str = Field(..., description='File identifier', pattern='^[A-Za-z0-9-]+$')
    grantedToOrgId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    grantedToUserId: str | None = Field(
        None,
        description='Specific user within org (if omitted, entire org has access)',
        pattern='^[A-Za-z0-9-]+$',
    )
    grantedByUserId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    grantedAt: str = Field(
        ...,
        pattern='^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d+([+-][0-2]\\d:[0-5]\\d|Z)$',
    )
    expiresAt: str | None = Field(
        None,
        description='Optional expiration',
        pattern='^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d+([+-][0-2]\\d:[0-5]\\d|Z)$',
    )
    permissions: list[FilePermission]
    grantablePermissions: list[FilePermission] | None = Field(
        None, description='Maximum permissions this party can grant to others'
    )
    isDeny: bool | None = Field(
        None, description='Explicit deny (overrides all grants)'
    )
    revokedByUserId: str | None = Field(
        None, description='Revocation tracking', pattern='^[A-Za-z0-9-]+$'
    )
    revokedAt: str | None = Field(
        None,
        pattern='^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d+([+-][0-2]\\d:[0-5]\\d|Z)$',
    )
    revocationReason: str | None
    metadata: Any | None = Field(
        None,
        description='Additional metadata as JSON\nTODO: Post-beta - Consider removing if unused or replace with explicit typed fields',
    )
    createdAt: str = Field(
        ...,
        pattern='^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d+([+-][0-2]\\d:[0-5]\\d|Z)$',
    )
    updatedAt: str = Field(
        ...,
        pattern='^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d+([+-][0-2]\\d:[0-5]\\d|Z)$',
    )


class FileAccessMap(RootModel[dict[str, FileAccess]]):
    root: dict[str, FileAccess]


class GenerateDownloadUrlResponseContent(BaseModel):
    downloadUrl: PresignedUrl


class GenerateUploadUrlResponseContent(BaseModel):
    uploadUrl: PresignedUrl


class GetAuditLogResponseContent(BaseModel):
    auditLog: AuditLog


class GetAuditStatisticsRequestContent(BaseModel):
    tableName: str | None = Field(None, description='Filter by table')
    startDate: str = Field(
        ...,
        description='Date range for statistics',
        pattern='^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d+([+-][0-2]\\d:[0-5]\\d|Z)$',
    )
    endDate: str = Field(
        ...,
        pattern='^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d+([+-][0-2]\\d:[0-5]\\d|Z)$',
    )
    groupBy: StatisticGrouping | None


class GetAuditStatisticsResponseContent(BaseModel):
    statistics: AuditStatistics
    timeSeries: list[TimeSeriesPoint] | None = Field(
        None, description='Time series data if groupBy is specified'
    )


class GetDealResponseContent(BaseModel):
    deal: Deal
    versions: DealVersionMap | None
    deliverables: DeliverableMap | None
    access: DealAccessMap | None


class GetDealVersionResponseContent(BaseModel):
    version: DealVersion
    deliverables: DeliverableMap | None


class GetFileResponseContent(BaseModel):
    file: File
    access: FileAccessMap | None
    downloadUrl: PresignedUrl | None


class GetOrgResponseContent(BaseModel):
    org: Org


class GetOrgThemeResponseContent(BaseModel):
    theme: OrgTheme


class GetProfileResponseContent(BaseModel):
    profile: UserProfile


class GrantDealAccessResponseContent(BaseModel):
    access: DealAccess


class GrantFileAccessResponseContent(BaseModel):
    access: FileAccess


class ListAuditLogsRequestContent(BaseModel):
    tableName: str | None
    recordType: RecordType | None
    operation: AuditOperation | None
    changedBy: str | None
    startDate: str | None = Field(
        None,
        pattern='^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d+([+-][0-2]\\d:[0-5]\\d|Z)$',
    )
    endDate: str | None = Field(
        None,
        pattern='^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d+([+-][0-2]\\d:[0-5]\\d|Z)$',
    )
    fieldName: str | None
    nextToken: str | None
    limit: float | None = Field(None, ge=1.0, le=100.0)


class ListAuditLogsResponseContent(BaseModel):
    logs: AuditLogMap
    nextToken: str | None = Field(None, description='Token for next page')


class ListDealAccessResponseContent(BaseModel):
    access: DealAccessMap
    nextToken: str | None = Field(None, description='Token for next page')


class ListDealThreadsResponseContent(BaseModel):
    dealThreads: DealThreadMap
    nextToken: str | None = Field(None, description='Token for next page')


class ListDeliverablesResponseContent(BaseModel):
    deliverables: DeliverableMap
    nextToken: str | None = Field(None, description='Token for next page')


class ListFileAccessResponseContent(BaseModel):
    access: FileAccessMap
    nextToken: str | None = Field(None, description='Token for next page')


class ListMeetingBotsResponseContent(BaseModel):
    bots: list[MeetingBotSummary]


class ListOrgMembersRequestContent(BaseModel):
    orgId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    role: str | None = Field(None, description='Filter by role')
    filters: list[OrgMemberFilter] | None = Field(
        None,
        description='Member status filters (if not specified, defaults to active only)',
    )
    nextToken: str | None = Field(
        None, description='Pagination cursor (encoded userId)'
    )
    limit: float | None = Field(None, description='Page size', ge=1.0, le=100.0)


class ListUserOrganizationsResponseContent(BaseModel):
    organizations: OrgMap
    nextToken: str | None = Field(None, description='Token for next page')


class NylasGetMessageResponseContent(BaseModel):
    requestId: str
    data: NylasMessage


class NylasGetThreadResponseContent(BaseModel):
    thread: NylasThread


class NylasListMessagesResponseContent(BaseModel):
    requestId: str
    data: list[NylasMessage]
    nextCursor: str | None = Field(None, description='Cursor for next page')


class NylasListThreadsResponseContent(BaseModel):
    threads: list[NylasThread]
    nextToken: str | None = Field(None, description='Token for next page')


class OrgCustomRole(BaseModel):
    customRoleId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    orgId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    name: str
    description: str | None
    permissions: list[OrgPermission]
    createdDate: str = Field(
        ...,
        pattern='^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d+([+-][0-2]\\d:[0-5]\\d|Z)$',
    )
    createdByUserId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    memberCount: float | None


class OrgCustomRoleMap(RootModel[dict[str, OrgCustomRole]]):
    root: dict[str, OrgCustomRole]


class OrgInvite(BaseModel):
    """
    Organization invitation
    """

    orgInviteId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    orgId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    invitedEmail: str = Field(..., pattern='^[\\w-\\.]+@[\\w-\\.]+\\.+[\\w-]{1,63}$')
    role: str
    customRoleId: str | None = Field(None, pattern='^[A-Za-z0-9-]+$')
    customRoleName: str | None
    customPermissions: list[OrgPermission] | None
    invitedByUserId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    invitedByProfile: UserProfile | None
    status: InviteStatus
    createdAt: str = Field(
        ...,
        pattern='^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d+([+-][0-2]\\d:[0-5]\\d|Z)$',
    )
    updatedAt: str = Field(
        ...,
        pattern='^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d+([+-][0-2]\\d:[0-5]\\d|Z)$',
    )
    expiresAt: str | None = Field(
        None,
        pattern='^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d+([+-][0-2]\\d:[0-5]\\d|Z)$',
    )
    acceptedAt: str | None = Field(
        None,
        pattern='^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d+([+-][0-2]\\d:[0-5]\\d|Z)$',
    )


class OrgInviteMap(RootModel[dict[str, OrgInvite]]):
    root: dict[str, OrgInvite]


class OrgMember(BaseModel):
    """
    Organization member
    """

    userId: str = Field(..., pattern='^[A-Za-z0-9-]+$')
    orgEmail: str = Field(..., pattern='^[\\w-\\.]+@[\\w-\\.]+\\.+[\\w-]{1,63}$')
    role: str
    customRoleId: str | None = Field(None, pattern='^[A-Za-z0-9-]+$')
    customRoleName: str | None
    customPermissions: list[OrgPermission] | None
    joinedDate: str = Field(
        ...,
        pattern='^\\d{4}-[01]\\d-[0-3]\\dT[0-2]\\d:[0-5]\\d:[0-5]\\d\\.\\d+([+-][0-2]\\d:[0-5]\\d|Z)$',
    )
    userProfile: UserProfile | None


class OrgMemberMap(RootModel[dict[str, OrgMember]]):
    root: dict[str, OrgMember]


class ResendOrgInviteResponseContent(BaseModel):
    invite: OrgInvite


class TranscriptParticipantEntry(BaseModel):
    """
    A single participant's contiguous speech segment within a transcript.
    One of these per speaker per continuous utterance.
    """

    participant: TranscriptParticipant
    words: list[TranscriptWord] = Field(
        ...,
        description='Words spoken by this participant, in order. Each carries its own\nstart/end timestamps relative to the recording.',
    )


class UpdateDealAccessResponseContent(BaseModel):
    access: DealAccess


class UpdateDealThreadResponseContent(BaseModel):
    success: bool
    dealThread: DealThread


class UpdateDeliverableResponseContent(BaseModel):
    deliverable: Deliverable


class UpdateFileAccessResponseContent(BaseModel):
    access: FileAccess


class UpdateOrgCustomRoleResponseContent(BaseModel):
    customRole: OrgCustomRole


class UpdateOrgMemberResponseContent(BaseModel):
    member: OrgMember


class UpdateProfileResponseContent(BaseModel):
    profile: UserProfile


class AcceptOrgInviteResponseContent(BaseModel):
    organization: Org
    member: OrgMember


class CreateDealThreadResponseContent(BaseModel):
    success: bool
    dealThread: DealThread


class CreateDeliverableResponseContent(BaseModel):
    deliverable: Deliverable


class CreateOrgCustomRoleResponseContent(BaseModel):
    customRole: OrgCustomRole


class CreateOrgInviteResponseContent(BaseModel):
    invites: OrgInviteMap
    failedEmails: list[FailedEmail] | None


class GetMeetingTranscriptResponseContent(BaseModel):
    transcript: list[TranscriptParticipantEntry] | None = Field(
        None,
        description='Parsed transcript. Absent while Recall is still processing, or when\nthe meeting ended with no captured speech.',
    )


class ListOrgCustomRolesResponseContent(BaseModel):
    roles: OrgCustomRoleMap
    nextToken: str | None = Field(None, description='Token for next page')


class ListOrgInvitesResponseContent(BaseModel):
    invites: OrgInviteMap
    nextToken: str | None = Field(None, description='Token for next page')


class ListOrgMembersResponseContent(BaseModel):
    members: OrgMemberMap
    nextToken: str | None = Field(None, description='Token for next page')
