/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/deleteContract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["DeleteContract"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/getContract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["GetContract"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/getContractReadURL": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["GetContractReadURL"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/getProfile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["GetProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/getProfilePicture": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["GetProfilePicture"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/getSpecialContract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["GetSpecialContract"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/listContracts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ListContracts"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/listSpecialContracts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ListSpecialContracts"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notARealEndpoint": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ExposeTypes"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CreateOrg"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["DeleteOrg"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["GetOrg"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/getOrgPicture": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["GetOrgPicture"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/getOrgTheme": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["GetOrgTheme"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/invites/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AcceptOrgInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/invites/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CancelOrgInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/invites/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CreateOrgInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/invites/decline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["DeclineOrgInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/invites/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ListOrgInvites"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/invites/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ResendOrgInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/listUserOrganizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ListUserOrganizations"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/members/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ListOrgMembers"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/removeMember": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["RemoveOrgMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/roles/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CreateOrgCustomRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/roles/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["DeleteOrgCustomRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/roles/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ListOrgCustomRoles"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/roles/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["UpdateOrgCustomRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/transferOwnership": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["TransferOrgOwnership"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["UpdateOrg"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/updateMember": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["UpdateOrgMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/updateOrgTheme": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["UpdateOrgTheme"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/uploadOrgPicture": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["UploadOrgPicture"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Ping"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shareContract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ShareContract"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/updateContract": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["UpdateContract"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/updateProfile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["UpdateProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploadProfilePicture": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["UploadProfilePicture"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploadURL": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["GetUploadURL"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AcceptOrgInviteRequestContent: {
            orgId: string;
            inviteId: string;
        };
        AcceptOrgInviteResponseContent: {
            success: boolean;
            organization: components["schemas"]["Org"];
            member: components["schemas"]["OrgMember"];
        };
        /** @enum {string} */
        AccountType: AccountType;
        AuthenticationErrorResponseContent: {
            message: string;
        };
        CancelOrgInviteRequestContent: {
            orgId: string;
            inviteId: string;
        };
        CancelOrgInviteResponseContent: {
            success: boolean;
        };
        ContractAnalysisRecord: {
            contractId: string;
            name: string;
            type: components["schemas"]["ContractType"];
            status: components["schemas"]["ContractStatus"];
            uploadedOn: string;
            ownerId: string;
            eqCards?: components["schemas"]["EqModeData"];
            iqData: components["schemas"]["IqModeData"];
            extractedType?: components["schemas"]["ContractType"];
            parties?: string[];
            terms?: components["schemas"]["ExtractionTermMap"];
            variables?: components["schemas"]["ContractVariableMap"];
            contractTexts?: components["schemas"]["ContractTexts"];
            sharedUsers?: components["schemas"]["SharedUserDetails"][];
            hasTTS?: boolean;
            isSpecial?: boolean;
        };
        ContractExtractionResult: {
            extractedType?: components["schemas"]["ContractType"];
            parties?: string[];
            terms?: components["schemas"]["ExtractionTermMap"];
            variables?: components["schemas"]["ContractVariableMap"];
            contractTexts?: components["schemas"]["ContractTexts"];
        };
        ContractMetadata: {
            contractId: string;
            name: string;
            type: components["schemas"]["ContractType"];
            status: components["schemas"]["ContractStatus"];
            uploadedOn: string;
            ownerId: string;
            sharedUsers?: components["schemas"]["SharedUserDetails"][];
            isOwner?: boolean;
            hasTTS?: boolean;
            isSpecial?: boolean;
        };
        /** @enum {string} */
        ContractStatus: ContractStatus;
        ContractSummaryItem: {
            contractId: string;
            name: string;
            /** Format: double */
            uploadedOn: number;
            type: components["schemas"]["ContractType"];
            status: components["schemas"]["ContractStatus"];
            isOwner: boolean;
            ownerId: string;
            sharedWith?: string[];
            sharedUsers?: string[];
            sharedEmails?: string[];
        };
        ContractTexts: {
            originalText?: components["schemas"]["PlainText"];
            taggedText?: components["schemas"]["TaggedText"];
        };
        /** @enum {string} */
        ContractType: ContractType;
        ContractVariable: {
            name: string;
            type: components["schemas"]["ContractVariableType"];
            id: string;
            value?: string;
            level?: number;
            /** Format: float */
            confidence?: number;
            firstOccurrence?: number;
            context?: string;
            variations?: string[];
            referencedSection?: string;
            definitionCitation?: string;
        };
        ContractVariableMap: {
            [key: string]: components["schemas"]["ContractVariable"];
        };
        /** @enum {string} */
        ContractVariableType: ContractVariableType;
        CreateOrgCustomRoleRequestContent: {
            orgId: string;
            name: string;
            description?: string;
            permissions: components["schemas"]["OrgPermission"][];
        };
        CreateOrgCustomRoleResponseContent: {
            success: boolean;
            customRole: components["schemas"]["OrgCustomRole"];
        };
        CreateOrgInviteRequestContent: {
            orgId: string;
            emails: string[];
            role: components["schemas"]["OrgRole"];
            customRoleId?: string;
            orgEmail?: string;
        };
        CreateOrgInviteResponseContent: {
            success: boolean;
            invites: components["schemas"]["OrgInviteMap"];
            failedEmails?: string[];
        };
        CreateOrgRequestContent: {
            name: string;
            type: components["schemas"]["OrgType"];
            description?: string;
            website?: string;
            billingEmail: string;
        };
        CreateOrgResponseContent: {
            success: boolean;
            org: components["schemas"]["Org"];
        };
        DeclineOrgInviteRequestContent: {
            orgId: string;
            inviteId: string;
        };
        DeclineOrgInviteResponseContent: {
            success: boolean;
        };
        DeleteContractRequestContent: {
            contractId: string;
        };
        DeleteContractResponseContent: {
            success: boolean;
        };
        DeleteOrgCustomRoleRequestContent: {
            orgId: string;
            customRoleId: string;
        };
        DeleteOrgCustomRoleResponseContent: {
            success: boolean;
        };
        DeleteOrgRequestContent: {
            orgId: string;
        };
        DeleteOrgResponseContent: {
            success: boolean;
        };
        /** @enum {string} */
        DurationType: DurationType;
        EmptyStructure: Record<string, never>;
        /** @enum {string} */
        EqCardKey: EqCardKey;
        /** @enum {string} */
        EqCardType: EqCardType;
        EqCardUniqueData: {
            MONEY_RECEIVED: components["schemas"]["EqMoneyCard"];
        } | {
            OWNERSHIP: components["schemas"]["EqOwnershipCard"];
        } | {
            RESPONSIBILITIES: components["schemas"]["EqResponsibilitiesCard"];
        } | {
            DURATION: components["schemas"]["EqDurationCard"];
        } | {
            LEGAL: components["schemas"]["EqLegalCard"];
        } | {
            EMPTY: components["schemas"]["EmptyStructure"];
        };
        EqDurationCard: {
            durationType: components["schemas"]["DurationType"];
            durationText: string;
            durationDetails?: components["schemas"]["SimpleTermDescription"][];
        };
        EqLegalCard: {
            risks: string;
            costs: string;
            legal: string;
        };
        EqModeCard: {
            id: components["schemas"]["EqCardKey"];
            title: string;
            type: components["schemas"]["EqCardType"];
            cardUniqueData: components["schemas"]["EqCardUniqueData"];
            /** @description Deprecated, use subTitle Instead */
            eqTitle?: string;
            subTitle?: string;
            /** @description Deprecated, this should be in the in a custom subtype */
            totalAdvance?: string;
            /** @description Deprecated, this should be in the in a custom subtype */
            items?: components["schemas"]["EqModeItem"][];
            /** @description Deprecated, use the ttsSrcUrl */
            audioSrc?: string;
            ttsSrcUrl?: string;
            flags?: components["schemas"]["EqModeCardFlag"][];
        };
        EqModeCardFlag: {
            severity: components["schemas"]["FlagSeverity"];
            context: string;
            referenceKey: string;
        };
        EqModeCardMap: {
            [key: string]: components["schemas"]["EqModeCard"];
        };
        EqModeData: {
            cards?: components["schemas"]["EqModeCardMap"];
        };
        /** @description Deprecated */
        EqModeItem: {
            title?: string;
            value?: string;
        };
        EqMoneyCard: {
            majorNumber: string;
            paidAfterList: string[];
        };
        EqOwnershipCard: {
            ownershipTerms: components["schemas"]["SimpleTermDescription"][];
        };
        EqResponsibilitiesCard: {
            responsibilities: components["schemas"]["SimpleTermDescription"][];
        };
        ExposeTypesResponseContent: {
            contractAnalysisRecord?: components["schemas"]["ContractAnalysisRecord"];
        };
        ExtractionTerm: {
            name: string;
            definition: string;
            unitType: string;
            explanation: string;
            notes: string;
            citation: string;
            fixedValues?: components["schemas"]["FixedValueTermInference"];
            fixedValueGuideline?: string;
            originalValue?: string;
        };
        ExtractionTermMap: {
            [key: string]: components["schemas"]["ExtractionTerm"];
        };
        FixedTermValue: {
            unit: string;
            value: string;
            name?: string;
            /** Format: float */
            numericValue?: number;
            condition?: string;
        };
        FixedValueTermInference: {
            primary: components["schemas"]["FixedTermValue"];
            subterms?: components["schemas"]["FixedTermValue"][];
        };
        /** @enum {string} */
        FlagSeverity: FlagSeverity;
        GetContractReadURLRequestContent: {
            contractId: string;
        };
        GetContractReadURLResponseContent: {
            url: string;
        };
        GetContractRequestContent: {
            contractId: string;
        };
        GetContractResponseContent: {
            contractId: string;
            ownerId: string;
            name: string;
            type: components["schemas"]["ContractType"];
            eqData?: components["schemas"]["EqModeData"];
            iqData?: components["schemas"]["IqModeData"];
            contractExtraction?: components["schemas"]["ContractExtractionResult"];
            sharedWith?: string[];
            isOwner?: boolean;
        };
        GetOrgPictureRequestContent: {
            orgId: string;
        };
        GetOrgPictureResponseContent: {
            profilePictureURL: string;
        };
        GetOrgRequestContent: {
            orgId: string;
        };
        GetOrgResponseContent: {
            org: components["schemas"]["Org"];
        };
        GetOrgThemeRequestContent: {
            orgId: string;
        };
        GetOrgThemeResponseContent: {
            theme: components["schemas"]["OrgTheme"];
        };
        GetProfilePictureRequestContent: {
            userId?: string;
        };
        GetProfilePictureResponseContent: {
            profilePictureURL: string;
        };
        GetProfileRequestContent: {
            userId?: string;
        };
        GetProfileResponseContent: {
            userId: string;
            profile: components["schemas"]["UserProfile"];
        };
        GetSpecialContractRequestContent: {
            contractId: string;
        };
        GetSpecialContractResponseContent: {
            contractId: string;
            name: string;
            type: components["schemas"]["ContractType"];
            eqmode: unknown;
            sections: unknown;
            isOwner: boolean;
            ownerId: string;
            sharedWith: string[];
        };
        GetUploadURLRequestContent: {
            name: string;
        };
        GetUploadURLResponseContent: {
            url_info: components["schemas"]["PresignedPostData"];
        };
        InternalServerErrorResponseContent: {
            message: string;
        };
        /** @enum {string} */
        InviteStatus: InviteStatus;
        IqModeData: {
            iqModeData?: components["schemas"]["IqModePerspectiveMap"];
        };
        IqModePerspective: {
            sections: components["schemas"]["IqModeSectionMap"];
        };
        IqModePerspectiveMap: {
            [key: string]: components["schemas"]["IqModePerspective"];
        };
        IqModeQuestion: {
            question: components["schemas"]["TaggedText"];
            answer: components["schemas"]["TaggedText"];
            ttsSrcUrl?: string;
        };
        IqModeSection: {
            id: components["schemas"]["IqModeSectionKey"];
            sectionTitle: string;
            questions: components["schemas"]["IqModeQuestion"][];
        };
        /** @enum {string} */
        IqModeSectionKey: IqModeSectionKey;
        IqModeSectionMap: {
            [key: string]: components["schemas"]["IqModeSection"];
        };
        ListContractsResponseContent: {
            /** @description Deprecation path (v0.5) */
            owned?: components["schemas"]["ContractSummaryItem"][];
            /** @description Deprecation path (v0.5) */
            shared?: components["schemas"]["ContractSummaryItem"][];
            /** @description v1 */
            contracts?: components["schemas"]["ContractMetadata"][];
        };
        ListOrgCustomRolesRequestContent: {
            orgId: string;
        };
        ListOrgCustomRolesResponseContent: {
            roles: components["schemas"]["OrgCustomRoleMap"];
        };
        ListOrgInvitesRequestContent: {
            orgId: string;
            status?: components["schemas"]["InviteStatus"];
        };
        ListOrgInvitesResponseContent: {
            invites: components["schemas"]["OrgInviteMap"];
        };
        ListOrgMembersRequestContent: {
            orgId: string;
        };
        ListOrgMembersResponseContent: {
            members: components["schemas"]["OrgMemberMap"];
        };
        ListSpecialContractsResponseContent: {
            owned: components["schemas"]["ContractSummaryItem"][];
            shared: components["schemas"]["ContractSummaryItem"][];
        };
        ListUserOrganizationsResponseContent: {
            organizations: components["schemas"]["Org"][];
        };
        Org: {
            orgId: string;
            name: string;
            type: components["schemas"]["OrgType"];
            primaryOwner: string;
            description?: string;
            website?: string;
            logoUrl?: string;
            billingEmail?: string;
            createdDate: string;
            memberCount?: number;
            userRole?: components["schemas"]["OrgRole"];
            contractCount?: number;
            inviteCount?: number;
            roleCount?: number;
        };
        OrgCustomRole: {
            customRoleId: string;
            orgId: string;
            name: string;
            description?: string;
            permissions: components["schemas"]["OrgPermission"][];
            createdDate: string;
            createdBy: string;
            memberCount?: number;
        };
        OrgCustomRoleMap: {
            [key: string]: components["schemas"]["OrgCustomRole"];
        };
        OrgInvite: {
            inviteId: string;
            orgId: string;
            invitedEmail: string;
            role: components["schemas"]["OrgRole"];
            customRoleId?: string;
            customRoleName?: string;
            customPermissions?: components["schemas"]["OrgPermission"][];
            invitedBy: string;
            invitedByProfile?: components["schemas"]["UserProfile"];
            status: components["schemas"]["InviteStatus"];
            createdDate: string;
            expiresDate?: string;
        };
        OrgInviteMap: {
            [key: string]: components["schemas"]["OrgInvite"];
        };
        OrgMember: {
            userId: string;
            orgEmail: string;
            role: components["schemas"]["OrgRole"];
            customRoleId?: string;
            customRoleName?: string;
            customPermissions?: components["schemas"]["OrgPermission"][];
            joinedDate: string;
            userProfile?: components["schemas"]["UserProfile"];
        };
        OrgMemberMap: {
            [key: string]: components["schemas"]["OrgMember"];
        };
        /** @enum {string} */
        OrgPermission: OrgPermission;
        /** @enum {string} */
        OrgRole: OrgRole;
        OrgTheme: {
            primaryColor?: string;
            secondaryColor?: string;
            accentColor?: string;
        };
        /** @enum {string} */
        OrgType: OrgType;
        PingResponseContent: {
            message: string;
        };
        PlainText: {
            text: string;
        };
        PresignedPostData: {
            url: string;
            fields: unknown;
        };
        ProcessingIncompleteErrorResponseContent: {
            message: string;
        };
        RemoveOrgMemberRequestContent: {
            orgId: string;
            userId: string;
        };
        RemoveOrgMemberResponseContent: {
            success: boolean;
        };
        ResendOrgInviteRequestContent: {
            orgId: string;
            inviteId: string;
            expiresDate?: string;
        };
        ResendOrgInviteResponseContent: {
            success: boolean;
            invite: components["schemas"]["OrgInvite"];
        };
        ResourceNotFoundErrorResponseContent: {
            message: string;
        };
        ShareContractRequestContent: {
            contractId: string;
            emailsToAdd?: string[];
            emailsToRemove?: string[];
        };
        ShareContractResponseContent: {
            success: boolean;
            contractId: string;
            sharedWith: components["schemas"]["SharedUserDetails"][];
            added?: string[];
            removed?: string[];
            invalidRemoves?: string[];
        };
        SharedUserDetails: {
            sharedWithUserId: string;
            sharedByUserId: string;
            sharedWithUserEmail: string;
            /** Format: double */
            sharedTime: number;
        };
        SimpleTermDescription: {
            title: string;
            description: string;
        };
        TaggedText: {
            text: string;
        };
        TransferOrgOwnershipRequestContent: {
            orgId: string;
            newOwnerId: string;
        };
        TransferOrgOwnershipResponseContent: {
            success: boolean;
            org: components["schemas"]["Org"];
        };
        UpdateContractRequestContent: {
            contractId: string;
            name: string;
        };
        UpdateContractResponseContent: {
            success: boolean;
        };
        UpdateOrgCustomRoleRequestContent: {
            orgId: string;
            customRoleId: string;
            name?: string;
            description?: string;
            permissions?: components["schemas"]["OrgPermission"][];
        };
        UpdateOrgCustomRoleResponseContent: {
            success: boolean;
            customRole: components["schemas"]["OrgCustomRole"];
        };
        UpdateOrgMemberRequestContent: {
            orgId: string;
            userId: string;
            role?: components["schemas"]["OrgRole"];
            customRoleId?: string;
            orgEmail?: string;
        };
        UpdateOrgMemberResponseContent: {
            success: boolean;
            member: components["schemas"]["OrgMember"];
        };
        UpdateOrgRequestContent: {
            orgId: string;
            name?: string;
            description?: string;
            website?: string;
            billingEmail?: string;
        };
        UpdateOrgResponseContent: {
            success: boolean;
            org: components["schemas"]["Org"];
        };
        UpdateOrgThemeRequestContent: {
            orgId: string;
            theme: components["schemas"]["OrgTheme"];
        };
        UpdateOrgThemeResponseContent: {
            success: boolean;
            theme: components["schemas"]["OrgTheme"];
        };
        UpdateProfileRequestContent: {
            firstName?: string;
            lastName?: string;
            displayName?: string;
            accountType?: components["schemas"]["AccountType"];
            bio?: string;
            isOver18?: boolean;
        };
        UpdateProfileResponseContent: {
            success: boolean;
            message: string;
            userId: string;
            updatedFields?: string[];
        };
        UploadOrgPictureRequestContent: {
            orgId: string;
        };
        UploadOrgPictureResponseContent: {
            url_info: components["schemas"]["PresignedPostData"];
        };
        UploadProfilePictureResponseContent: {
            url_info: components["schemas"]["PresignedPostData"];
        };
        UserProfile: {
            userId?: string;
            firstName?: string;
            lastName?: string;
            displayName?: string;
            email?: string;
            accountType?: components["schemas"]["AccountType"];
            bio?: string;
        };
        ValidationErrorResponseContent: {
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    DeleteContract: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteContractRequestContent"];
            };
        };
        responses: {
            /** @description DeleteContract 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteContractResponseContent"];
                };
            };
            /** @description ResourceNotFoundError 400 response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceNotFoundErrorResponseContent"];
                };
            };
            /** @description InternalServerError 500 response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerErrorResponseContent"];
                };
            };
        };
    };
    GetContract: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GetContractRequestContent"];
            };
        };
        responses: {
            /** @description GetContract 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetContractResponseContent"];
                };
            };
            /** @description ProcessingIncompleteError 400 response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessingIncompleteErrorResponseContent"];
                };
            };
            /** @description InternalServerError 500 response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerErrorResponseContent"];
                };
            };
        };
    };
    GetContractReadURL: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GetContractReadURLRequestContent"];
            };
        };
        responses: {
            /** @description GetContractReadURL 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetContractReadURLResponseContent"];
                };
            };
            /** @description ResourceNotFoundError 400 response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceNotFoundErrorResponseContent"];
                };
            };
            /** @description InternalServerError 500 response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerErrorResponseContent"];
                };
            };
        };
    };
    GetProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["GetProfileRequestContent"];
            };
        };
        responses: {
            /** @description GetProfile 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetProfileResponseContent"];
                };
            };
            /** @description ResourceNotFoundError 400 response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceNotFoundErrorResponseContent"];
                };
            };
            /** @description InternalServerError 500 response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerErrorResponseContent"];
                };
            };
        };
    };
    GetProfilePicture: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["GetProfilePictureRequestContent"];
            };
        };
        responses: {
            /** @description GetProfilePicture 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetProfilePictureResponseContent"];
                };
            };
            /** @description ResourceNotFoundError 400 response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceNotFoundErrorResponseContent"];
                };
            };
            /** @description InternalServerError 500 response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerErrorResponseContent"];
                };
            };
        };
    };
    GetSpecialContract: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GetSpecialContractRequestContent"];
            };
        };
        responses: {
            /** @description GetSpecialContract 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetSpecialContractResponseContent"];
                };
            };
            /** @description ProcessingIncompleteError 400 response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessingIncompleteErrorResponseContent"];
                };
            };
            /** @description InternalServerError 500 response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerErrorResponseContent"];
                };
            };
        };
    };
    ListContracts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ListContracts 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListContractsResponseContent"];
                };
            };
            /** @description AuthenticationError 400 response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationErrorResponseContent"];
                };
            };
            /** @description InternalServerError 500 response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerErrorResponseContent"];
                };
            };
        };
    };
    ListSpecialContracts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ListSpecialContracts 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListSpecialContractsResponseContent"];
                };
            };
            /** @description AuthenticationError 400 response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationErrorResponseContent"];
                };
            };
            /** @description InternalServerError 500 response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerErrorResponseContent"];
                };
            };
        };
    };
    ExposeTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ExposeTypes 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExposeTypesResponseContent"];
                };
            };
        };
    };
    CreateOrg: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrgRequestContent"];
            };
        };
        responses: {
            /** @description CreateOrg 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateOrgResponseContent"];
                };
            };
            /** @description ValidationError 400 response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponseContent"];
                };
            };
            /** @description InternalServerError 500 response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerErrorResponseContent"];
                };
            };
        };
    };
    DeleteOrg: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteOrgRequestContent"];
            };
        };
        responses: {
            /** @description DeleteOrg 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteOrgResponseContent"];
                };
            };
            /** @description ValidationError 400 response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponseContent"];
                };
            };
            /** @description InternalServerError 500 response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerErrorResponseContent"];
                };
            };
        };
    };
    GetOrg: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GetOrgRequestContent"];
            };
        };
        responses: {
            /** @description GetOrg 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetOrgResponseContent"];
                };
            };
            /** @description ResourceNotFoundError 400 response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceNotFoundErrorResponseContent"];
                };
            };
            /** @description InternalServerError 500 response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerErrorResponseContent"];
                };
            };
        };
    };
    GetOrgPicture: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GetOrgPictureRequestContent"];
            };
        };
        responses: {
            /** @description GetOrgPicture 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetOrgPictureResponseContent"];
                };
            };
            /** @description ResourceNotFoundError 400 response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceNotFoundErrorResponseContent"];
                };
            };
            /** @description InternalServerError 500 response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerErrorResponseContent"];
                };
            };
        };
    };
    GetOrgTheme: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GetOrgThemeRequestContent"];
            };
        };
        responses: {
            /** @description GetOrgTheme 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetOrgThemeResponseContent"];
                };
            };
            /** @description ResourceNotFoundError 400 response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceNotFoundErrorResponseContent"];
                };
            };
            /** @description InternalServerError 500 response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerErrorResponseContent"];
                };
            };
        };
    };
    AcceptOrgInvite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptOrgInviteRequestContent"];
            };
        };
        responses: {
            /** @description AcceptOrgInvite 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcceptOrgInviteResponseContent"];
                };
            };
            /** @description ValidationError 400 response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponseContent"];
                };
            };
            /** @description InternalServerError 500 response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerErrorResponseContent"];
                };
            };
        };
    };
    CancelOrgInvite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelOrgInviteRequestContent"];
            };
        };
        responses: {
            /** @description CancelOrgInvite 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancelOrgInviteResponseContent"];
                };
            };
            /** @description ValidationError 400 response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponseContent"];
                };
            };
            /** @description InternalServerError 500 response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerErrorResponseContent"];
                };
            };
        };
    };
    CreateOrgInvite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrgInviteRequestContent"];
            };
        };
        responses: {
            /** @description CreateOrgInvite 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateOrgInviteResponseContent"];
                };
            };
            /** @description ValidationError 400 response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponseContent"];
                };
            };
            /** @description InternalServerError 500 response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerErrorResponseContent"];
                };
            };
        };
    };
    DeclineOrgInvite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeclineOrgInviteRequestContent"];
            };
        };
        responses: {
            /** @description DeclineOrgInvite 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeclineOrgInviteResponseContent"];
                };
            };
            /** @description ValidationError 400 response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponseContent"];
                };
            };
            /** @description InternalServerError 500 response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerErrorResponseContent"];
                };
            };
        };
    };
    ListOrgInvites: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ListOrgInvitesRequestContent"];
            };
        };
        responses: {
            /** @description ListOrgInvites 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListOrgInvitesResponseContent"];
                };
            };
            /** @description ResourceNotFoundError 400 response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceNotFoundErrorResponseContent"];
                };
            };
            /** @description InternalServerError 500 response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerErrorResponseContent"];
                };
            };
        };
    };
    ResendOrgInvite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResendOrgInviteRequestContent"];
            };
        };
        responses: {
            /** @description ResendOrgInvite 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResendOrgInviteResponseContent"];
                };
            };
            /** @description ValidationError 400 response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponseContent"];
                };
            };
            /** @description InternalServerError 500 response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerErrorResponseContent"];
                };
            };
        };
    };
    ListUserOrganizations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ListUserOrganizations 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListUserOrganizationsResponseContent"];
                };
            };
            /** @description AuthenticationError 400 response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticationErrorResponseContent"];
                };
            };
            /** @description InternalServerError 500 response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerErrorResponseContent"];
                };
            };
        };
    };
    ListOrgMembers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ListOrgMembersRequestContent"];
            };
        };
        responses: {
            /** @description ListOrgMembers 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListOrgMembersResponseContent"];
                };
            };
            /** @description ResourceNotFoundError 400 response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceNotFoundErrorResponseContent"];
                };
            };
            /** @description InternalServerError 500 response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerErrorResponseContent"];
                };
            };
        };
    };
    RemoveOrgMember: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RemoveOrgMemberRequestContent"];
            };
        };
        responses: {
            /** @description RemoveOrgMember 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RemoveOrgMemberResponseContent"];
                };
            };
            /** @description ValidationError 400 response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponseContent"];
                };
            };
            /** @description InternalServerError 500 response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerErrorResponseContent"];
                };
            };
        };
    };
    CreateOrgCustomRole: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrgCustomRoleRequestContent"];
            };
        };
        responses: {
            /** @description CreateOrgCustomRole 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateOrgCustomRoleResponseContent"];
                };
            };
            /** @description ValidationError 400 response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponseContent"];
                };
            };
            /** @description InternalServerError 500 response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerErrorResponseContent"];
                };
            };
        };
    };
    DeleteOrgCustomRole: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteOrgCustomRoleRequestContent"];
            };
        };
        responses: {
            /** @description DeleteOrgCustomRole 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteOrgCustomRoleResponseContent"];
                };
            };
            /** @description ValidationError 400 response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponseContent"];
                };
            };
            /** @description InternalServerError 500 response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerErrorResponseContent"];
                };
            };
        };
    };
    ListOrgCustomRoles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ListOrgCustomRolesRequestContent"];
            };
        };
        responses: {
            /** @description ListOrgCustomRoles 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListOrgCustomRolesResponseContent"];
                };
            };
            /** @description ResourceNotFoundError 400 response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceNotFoundErrorResponseContent"];
                };
            };
            /** @description InternalServerError 500 response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerErrorResponseContent"];
                };
            };
        };
    };
    UpdateOrgCustomRole: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOrgCustomRoleRequestContent"];
            };
        };
        responses: {
            /** @description UpdateOrgCustomRole 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateOrgCustomRoleResponseContent"];
                };
            };
            /** @description ValidationError 400 response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponseContent"];
                };
            };
            /** @description InternalServerError 500 response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerErrorResponseContent"];
                };
            };
        };
    };
    TransferOrgOwnership: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransferOrgOwnershipRequestContent"];
            };
        };
        responses: {
            /** @description TransferOrgOwnership 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransferOrgOwnershipResponseContent"];
                };
            };
            /** @description ValidationError 400 response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponseContent"];
                };
            };
            /** @description InternalServerError 500 response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerErrorResponseContent"];
                };
            };
        };
    };
    UpdateOrg: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOrgRequestContent"];
            };
        };
        responses: {
            /** @description UpdateOrg 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateOrgResponseContent"];
                };
            };
            /** @description ValidationError 400 response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponseContent"];
                };
            };
            /** @description InternalServerError 500 response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerErrorResponseContent"];
                };
            };
        };
    };
    UpdateOrgMember: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOrgMemberRequestContent"];
            };
        };
        responses: {
            /** @description UpdateOrgMember 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateOrgMemberResponseContent"];
                };
            };
            /** @description ValidationError 400 response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponseContent"];
                };
            };
            /** @description InternalServerError 500 response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerErrorResponseContent"];
                };
            };
        };
    };
    UpdateOrgTheme: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOrgThemeRequestContent"];
            };
        };
        responses: {
            /** @description UpdateOrgTheme 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateOrgThemeResponseContent"];
                };
            };
            /** @description ValidationError 400 response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponseContent"];
                };
            };
            /** @description InternalServerError 500 response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerErrorResponseContent"];
                };
            };
        };
    };
    UploadOrgPicture: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadOrgPictureRequestContent"];
            };
        };
        responses: {
            /** @description UploadOrgPicture 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadOrgPictureResponseContent"];
                };
            };
            /** @description ResourceNotFoundError 400 response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceNotFoundErrorResponseContent"];
                };
            };
            /** @description InternalServerError 500 response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerErrorResponseContent"];
                };
            };
        };
    };
    Ping: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ping 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PingResponseContent"];
                };
            };
        };
    };
    ShareContract: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShareContractRequestContent"];
            };
        };
        responses: {
            /** @description ShareContract 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShareContractResponseContent"];
                };
            };
            /** @description ValidationError 400 response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponseContent"];
                };
            };
            /** @description InternalServerError 500 response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerErrorResponseContent"];
                };
            };
        };
    };
    UpdateContract: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateContractRequestContent"];
            };
        };
        responses: {
            /** @description UpdateContract 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateContractResponseContent"];
                };
            };
            /** @description ValidationError 400 response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponseContent"];
                };
            };
            /** @description InternalServerError 500 response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerErrorResponseContent"];
                };
            };
        };
    };
    UpdateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequestContent"];
            };
        };
        responses: {
            /** @description UpdateProfile 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateProfileResponseContent"];
                };
            };
            /** @description ValidationError 400 response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponseContent"];
                };
            };
            /** @description InternalServerError 500 response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerErrorResponseContent"];
                };
            };
        };
    };
    UploadProfilePicture: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description UploadProfilePicture 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadProfilePictureResponseContent"];
                };
            };
            /** @description ResourceNotFoundError 400 response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceNotFoundErrorResponseContent"];
                };
            };
            /** @description InternalServerError 500 response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerErrorResponseContent"];
                };
            };
        };
    };
    GetUploadURL: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GetUploadURLRequestContent"];
            };
        };
        responses: {
            /** @description GetUploadURL 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetUploadURLResponseContent"];
                };
            };
            /** @description ValidationError 400 response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponseContent"];
                };
            };
            /** @description InternalServerError 500 response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerErrorResponseContent"];
                };
            };
        };
    };
}
export enum AccountType {
    artist = "artist",
    manager = "manager",
    lawyer = "lawyer",
    producer = "producer",
    publisher = "publisher",
    executive = "executive"
}
export enum ContractStatus {
    processing = "processing",
    awaiting_upload = "awaiting_upload",
    extracting_text = "extracting_text",
    eq_generation = "eq_generation",
    iq_generation = "iq_generation",
    variable_extraction = "variable_extraction",
    contract_markup = "contract_markup",
    tts_generation = "tts_generation",
    complete = "complete",
    error = "error"
}
export enum ContractType {
    recording = "recording",
    publishing = "publishing",
    management = "management",
    producer = "producer",
    services = "services",
    tbd = "tbd"
}
export enum ContractVariableType {
    eq_term = "eq_term",
    discovered_term = "discovered_term",
    external_term = "external_term",
    internal_citation = "internal_citation"
}
export enum DurationType {
    fixed = "fixed",
    indefinite = "indefinite",
    renewable = "renewable",
    other = "other"
}
export enum EqCardKey {
    moneyYouReceive = "moneyYouReceive",
    whatYouOwn = "whatYouOwn",
    whatYoureResponsibleFor = "whatYoureResponsibleFor",
    howLongThisDealLasts = "howLongThisDealLasts",
    risksCostsLegalStuff = "risksCostsLegalStuff"
}
export enum EqCardType {
    A = "A",
    B = "B"
}
export enum FlagSeverity {
    red = "red",
    yellow = "yellow",
    orange = "orange",
    blue = "blue"
}
export enum InviteStatus {
    pending = "pending",
    accepted = "accepted",
    declined = "declined",
    expired = "expired"
}
export enum IqModeSectionKey {
    earnings = "earnings",
    qualityOfRights = "qualityOfRights",
    usageObligations = "usageObligations",
    agreementLength = "agreementLength",
    liabilitySafeguards = "liabilitySafeguards"
}
export enum OrgPermission {
    manage_members = "manage_members",
    manage_billing = "manage_billing",
    manage_settings = "manage_settings",
    view_all_contracts = "view_all_contracts",
    manage_contracts = "manage_contracts",
    invite_users = "invite_users",
    manage_roles = "manage_roles",
    view_analytics = "view_analytics"
}
export enum OrgRole {
    primary_owner = "primary_owner",
    admin = "admin",
    billing_admin = "billing_admin",
    member = "member",
    viewer = "viewer",
    custom = "custom"
}
export enum OrgType {
    law_firm = "law_firm",
    record_label = "record_label",
    management_company = "management_company",
    publishing_company = "publishing_company",
    production_company = "production_company",
    talent_agency = "talent_agency",
    distribution_company = "distribution_company",
    other = "other"
}
