/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/organizations/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CreateOrg"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["DeleteOrg"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ListOrgInvitations"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/invitations/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CancelOrgInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/invitations/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ResendOrgInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["InviteToOrg"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/removeMember": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["RemoveOrgMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/roles/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CreateCustomRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/roles/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["DeleteCustomRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/roles/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["UpdateCustomRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/transferOwnership": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["TransferOrgOwnership"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["UpdateOrg"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/updateMember": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["UpdateOrgMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        AccountType: AccountType;
        CancelOrgInvitationRequestContent: {
            organizationId: string;
            invitationId: string;
        };
        CancelOrgInvitationResponseContent: {
            success: boolean;
        };
        CreateCustomRoleRequestContent: {
            organizationId: string;
            name: string;
            description?: string;
            permissions: components["schemas"]["OrgPermission"][];
        };
        CreateCustomRoleResponseContent: {
            success: boolean;
            customRole: components["schemas"]["CustomRole"];
        };
        CreateOrgRequestContent: {
            name: string;
            type: components["schemas"]["OrgType"];
            description?: string;
            website?: string;
            billingEmail?: string;
        };
        CreateOrgResponseContent: {
            success: boolean;
            organization: components["schemas"]["Org"];
        };
        CustomRole: {
            customRoleId: string;
            organizationId: string;
            name: string;
            description?: string;
            permissions: components["schemas"]["OrgPermission"][];
            createdDate: string;
            createdBy: string;
        };
        DeleteCustomRoleRequestContent: {
            organizationId: string;
            customRoleId: string;
        };
        DeleteCustomRoleResponseContent: {
            success: boolean;
        };
        DeleteOrgRequestContent: {
            organizationId: string;
        };
        DeleteOrgResponseContent: {
            success: boolean;
        };
        InternalServerErrorResponseContent: {
            message: string;
        };
        /** @enum {string} */
        InvitationStatus: InvitationStatus;
        InviteToOrgRequestContent: {
            organizationId: string;
            emails: string[];
            role: components["schemas"]["OrgRole"];
            customRoleId?: string;
            organizationEmail?: string;
        };
        InviteToOrgResponseContent: {
            success: boolean;
            invitations: components["schemas"]["OrgInvitation"][];
            failedEmails?: string[];
        };
        ListOrgInvitationsRequestContent: {
            organizationId: string;
            status?: components["schemas"]["InvitationStatus"];
        };
        ListOrgInvitationsResponseContent: {
            invitations: components["schemas"]["OrgInvitation"][];
        };
        Org: {
            organizationId: string;
            name: string;
            type: components["schemas"]["OrgType"];
            primaryOwner: string;
            description?: string;
            website?: string;
            billingEmail?: string;
            createdDate: string;
            memberCount?: number;
        };
        OrgInvitation: {
            invitationId: string;
            organizationId: string;
            invitedEmail: string;
            role: components["schemas"]["OrgRole"];
            customRoleId?: string;
            customRoleName?: string;
            customPermissions?: components["schemas"]["OrgPermission"][];
            invitedBy: string;
            status: components["schemas"]["InvitationStatus"];
            createdDate: string;
            expiresDate?: string;
            inviterProfile?: components["schemas"]["UserProfile"];
        };
        OrgMember: {
            userId: string;
            organizationEmail: string;
            role: components["schemas"]["OrgRole"];
            customRoleId?: string;
            customRoleName?: string;
            customPermissions?: components["schemas"]["OrgPermission"][];
            joinedDate: string;
            userProfile?: components["schemas"]["UserProfile"];
        };
        /** @enum {string} */
        OrgPermission: OrgPermission;
        /** @enum {string} */
        OrgRole: OrgRole;
        /** @enum {string} */
        OrgType: OrgType;
        RemoveOrgMemberRequestContent: {
            organizationId: string;
            userId: string;
        };
        RemoveOrgMemberResponseContent: {
            success: boolean;
        };
        ResendOrgInvitationRequestContent: {
            organizationId: string;
            invitationId: string;
        };
        ResendOrgInvitationResponseContent: {
            success: boolean;
            invitation: components["schemas"]["OrgInvitation"];
        };
        ResourceNotFoundErrorResponseContent: {
            message: string;
        };
        TransferOrgOwnershipRequestContent: {
            organizationId: string;
            newOwnerId: string;
        };
        TransferOrgOwnershipResponseContent: {
            success: boolean;
            organization: components["schemas"]["Org"];
        };
        UpdateCustomRoleRequestContent: {
            organizationId: string;
            customRoleId: string;
            name?: string;
            description?: string;
            permissions?: components["schemas"]["OrgPermission"][];
        };
        UpdateCustomRoleResponseContent: {
            success: boolean;
            customRole: components["schemas"]["CustomRole"];
        };
        UpdateOrgMemberRequestContent: {
            organizationId: string;
            userId: string;
            role?: components["schemas"]["OrgRole"];
            customRoleId?: string;
            organizationEmail?: string;
        };
        UpdateOrgMemberResponseContent: {
            success: boolean;
            member: components["schemas"]["OrgMember"];
        };
        UpdateOrgRequestContent: {
            organizationId: string;
            name?: string;
            description?: string;
            website?: string;
            billingEmail?: string;
        };
        UpdateOrgResponseContent: {
            success: boolean;
            organization: components["schemas"]["Org"];
        };
        UserProfile: {
            userId?: string;
            firstName?: string;
            lastName?: string;
            displayName?: string;
            email?: string;
            accountType?: components["schemas"]["AccountType"];
            bio?: string;
        };
        ValidationErrorResponseContent: {
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    CreateOrg: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrgRequestContent"];
            };
        };
        responses: {
            /** @description CreateOrg 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateOrgResponseContent"];
                };
            };
            /** @description ValidationError 400 response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponseContent"];
                };
            };
            /** @description InternalServerError 500 response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerErrorResponseContent"];
                };
            };
        };
    };
    DeleteOrg: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteOrgRequestContent"];
            };
        };
        responses: {
            /** @description DeleteOrg 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteOrgResponseContent"];
                };
            };
            /** @description ValidationError 400 response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponseContent"];
                };
            };
            /** @description InternalServerError 500 response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerErrorResponseContent"];
                };
            };
        };
    };
    ListOrgInvitations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ListOrgInvitationsRequestContent"];
            };
        };
        responses: {
            /** @description ListOrgInvitations 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListOrgInvitationsResponseContent"];
                };
            };
            /** @description ResourceNotFoundError 400 response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceNotFoundErrorResponseContent"];
                };
            };
            /** @description InternalServerError 500 response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerErrorResponseContent"];
                };
            };
        };
    };
    CancelOrgInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelOrgInvitationRequestContent"];
            };
        };
        responses: {
            /** @description CancelOrgInvitation 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CancelOrgInvitationResponseContent"];
                };
            };
            /** @description ValidationError 400 response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponseContent"];
                };
            };
            /** @description InternalServerError 500 response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerErrorResponseContent"];
                };
            };
        };
    };
    ResendOrgInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResendOrgInvitationRequestContent"];
            };
        };
        responses: {
            /** @description ResendOrgInvitation 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResendOrgInvitationResponseContent"];
                };
            };
            /** @description ValidationError 400 response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponseContent"];
                };
            };
            /** @description InternalServerError 500 response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerErrorResponseContent"];
                };
            };
        };
    };
    InviteToOrg: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteToOrgRequestContent"];
            };
        };
        responses: {
            /** @description InviteToOrg 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteToOrgResponseContent"];
                };
            };
            /** @description ValidationError 400 response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponseContent"];
                };
            };
            /** @description InternalServerError 500 response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerErrorResponseContent"];
                };
            };
        };
    };
    RemoveOrgMember: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RemoveOrgMemberRequestContent"];
            };
        };
        responses: {
            /** @description RemoveOrgMember 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RemoveOrgMemberResponseContent"];
                };
            };
            /** @description ValidationError 400 response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponseContent"];
                };
            };
            /** @description InternalServerError 500 response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerErrorResponseContent"];
                };
            };
        };
    };
    CreateCustomRole: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCustomRoleRequestContent"];
            };
        };
        responses: {
            /** @description CreateCustomRole 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateCustomRoleResponseContent"];
                };
            };
            /** @description ValidationError 400 response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponseContent"];
                };
            };
            /** @description InternalServerError 500 response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerErrorResponseContent"];
                };
            };
        };
    };
    DeleteCustomRole: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteCustomRoleRequestContent"];
            };
        };
        responses: {
            /** @description DeleteCustomRole 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteCustomRoleResponseContent"];
                };
            };
            /** @description ValidationError 400 response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponseContent"];
                };
            };
            /** @description InternalServerError 500 response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerErrorResponseContent"];
                };
            };
        };
    };
    UpdateCustomRole: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCustomRoleRequestContent"];
            };
        };
        responses: {
            /** @description UpdateCustomRole 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateCustomRoleResponseContent"];
                };
            };
            /** @description ValidationError 400 response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponseContent"];
                };
            };
            /** @description InternalServerError 500 response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerErrorResponseContent"];
                };
            };
        };
    };
    TransferOrgOwnership: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransferOrgOwnershipRequestContent"];
            };
        };
        responses: {
            /** @description TransferOrgOwnership 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransferOrgOwnershipResponseContent"];
                };
            };
            /** @description ValidationError 400 response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponseContent"];
                };
            };
            /** @description InternalServerError 500 response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerErrorResponseContent"];
                };
            };
        };
    };
    UpdateOrg: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOrgRequestContent"];
            };
        };
        responses: {
            /** @description UpdateOrg 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateOrgResponseContent"];
                };
            };
            /** @description ValidationError 400 response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponseContent"];
                };
            };
            /** @description InternalServerError 500 response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerErrorResponseContent"];
                };
            };
        };
    };
    UpdateOrgMember: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOrgMemberRequestContent"];
            };
        };
        responses: {
            /** @description UpdateOrgMember 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateOrgMemberResponseContent"];
                };
            };
            /** @description ValidationError 400 response */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponseContent"];
                };
            };
            /** @description InternalServerError 500 response */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerErrorResponseContent"];
                };
            };
        };
    };
}
export enum AccountType {
    artist = "artist",
    manager = "manager",
    lawyer = "lawyer",
    producer = "producer",
    publisher = "publisher",
    executive = "executive"
}
export enum InvitationStatus {
    pending = "pending",
    accepted = "accepted",
    declined = "declined",
    expired = "expired"
}
export enum OrgPermission {
    manage_members = "manage_members",
    manage_billing = "manage_billing",
    manage_settings = "manage_settings",
    view_all_contracts = "view_all_contracts",
    manage_contracts = "manage_contracts",
    invite_users = "invite_users",
    manage_roles = "manage_roles",
    view_analytics = "view_analytics"
}
export enum OrgRole {
    primary_owner = "primary_owner",
    admin = "admin",
    billing_admin = "billing_admin",
    member = "member",
    viewer = "viewer",
    custom = "custom"
}
export enum OrgType {
    law_firm = "law_firm",
    record_label = "record_label",
    management_company = "management_company",
    publishing_company = "publishing_company",
    production_company = "production_company",
    talent_agency = "talent_agency",
    distribution_company = "distribution_company",
    other = "other"
}
