/**
 * Non-autogenerated XML markup types
 * Shared between contract-tinkering (backend) and frontend
 *
 * DO NOT add to smithy-build.json - this file is maintained manually
 */

import { ContractVariableType, ContractVariable } from './index'

/**
 * Parsed XML variable tag attributes
 */
export interface VariableTagAttributes {
  type: ContractVariableType
  id: string
  instance?: string
  level?: number
}

/**
 * Result of parsing a <variable> tag
 */
export interface ParsedVariableTag {
  attributes: VariableTagAttributes
  innerText: string
  fullMatch: string
  startIndex: number
  endIndex: number
}

/**
 * Options for XML tag parsing
 */
export interface XmlParseOptions {
  /** If false, re-count instances instead of using backend values */
  preserveInstance?: boolean
  /** Validate attributes against ContractVariable data */
  validateAttributes?: boolean
}

/**
 * Validation result for a variable tag
 */
export interface ValidationResult {
  isValid: boolean
  errors: string[]
}
